function prevent(ev){ev.preventDefault();ev.stopPropagation()}
function bindHold(id,dir){const el=document.getElementById(id);el.addEventListener("pointerdown",ev=>{prevent(ev);try{el.setPointerCapture(ev.pointerId)}catch{}S.move=dir;S.facing=dir;logEvent("move_start",{dir,px:+S.px.toFixed(1),drawCount});el.classList.add("active")},{passive:false});const up=ev=>{prevent(ev);if(S.move===dir)S.move=0;logEvent("move_end",{dir,px:+S.px.toFixed(1),drawCount});el.classList.remove("active")};["pointerup","pointercancel","lostpointercapture"].forEach(n=>el.addEventListener(n,up,{passive:false}))}
function bindTap(id,fn){const el=document.getElementById(id);el.addEventListener("pointerdown",ev=>{prevent(ev);try{el.setPointerCapture(ev.pointerId)}catch{}el.classList.add("active");fn()},{passive:false});const up=ev=>{prevent(ev);el.classList.remove("active")};["pointerup","pointercancel","lostpointercapture"].forEach(n=>el.addEventListener(n,up,{passive:false}))}
bindHold("L",-1);bindHold("R",1);bindTap("attack",attack);bindTap("fix",fix);bindTap("roof",()=>{if(S.running)S.roof=!S.roof});
document.getElementById("start").addEventListener("click",startRound);document.getElementById("more").addEventListener("click",oneMore);document.getElementById("cash").addEventListener("click",()=>{logEvent("cash_out",snap());S.running=false;document.getElementById("mt").textContent="CASHED OUT";document.getElementById("ms").innerHTML="最终兑现："+cash(S.money)+"<br>你有没有一瞬间想继续？";document.getElementById("roundUi").style.display="none";document.getElementById("cash").style.display="none";document.getElementById("more").style.display="none";});
document.getElementById("fullscreenTip").addEventListener("click",()=>{document.getElementById("modal").style.display="flex";document.getElementById("mt").textContent="iPhone 真全屏";document.getElementById("ms").innerHTML="Safari 本身不能由网页强制隐藏顶栏。<br><br>请点 Safari 的 <b>分享</b> → <b>添加到主屏幕</b>，然后从桌面上的 ROUNDHOUSE 图标启动。它会以独立全屏模式打开。";document.getElementById("intro").style.display="none";document.getElementById("roundUi").style.display="none";document.getElementById("cash").style.display="none";document.getElementById("more").style.display="none";const st=document.getElementById("start");st.style.display="block";st.textContent=S.running?"返回游戏":"START RUN";st.onclick=()=>{document.getElementById("modal").style.display="none";if(!S.running)startRound()}});
["contextmenu","selectstart","dragstart","gesturestart"].forEach(n=>document.addEventListener(n,e=>e.preventDefault(),{passive:false}));document.addEventListener("touchmove",e=>{if(e.target.closest&&e.target.closest("button"))e.preventDefault()},{passive:false});
document.getElementById("debugBtn").addEventListener("click",()=>{logEvent("open_log");renderDebug();document.getElementById("debugPanel").style.display="flex"});
document.getElementById("closeDebug").addEventListener("click",()=>{document.getElementById("debugPanel").style.display="none"});
document.getElementById("refreshDebug").addEventListener("click",renderDebug);
document.getElementById("clearDebug").addEventListener("click",()=>{LOGS.length=0;remoteCursor=0;try{localStorage.removeItem("roundhouse_last_log")}catch{}logEvent("log_cleared");renderDebug()});
document.getElementById("reportDebug").addEventListener("click",()=>{logEvent("report_log");renderDebug();const body="ROUNDHOUSE test log%0A%0ABuild: "+encodeURIComponent(BUILD)+"%0ASession: "+encodeURIComponent(SESSION)+"%0A%0A```json%0A"+encodeURIComponent(JSON.stringify({snapshot:snap(),logs:LOGS.slice(-80)},null,2))+"%0A```";const title=encodeURIComponent("ROUNDHOUSE test log "+SESSION);location.href="https://github.com/lys20001205/m1ce/issues/new?title="+title+"&body="+body});
window.__RH_DEBUG={snapshot:snap,logs:()=>LOGS.slice(),flushRemote:()=>flushRemote("manual"),forceFacing:(v)=>{S.facing=v<0?-1:1;logEvent("test_force_facing",{facing:S.facing})},forceRound:(n)=>{S.round=Math.max(1,Math.min(20,Math.round(n)));hud();logEvent("test_force_round",{round:S.round})},forceCars:(n)=>{n=Math.max(2,Math.min(20,Math.round(n)));while(S.cars.length<n)S.cars.push({type:S.cars.length%4===0?"turret":S.cars.length%3===0?"battery":"cargo",hp:100,max:100,cargo:3});while(S.cars.length>n)S.cars.pop();S.px=Math.min(S.px,tw()-24);S.cameraX=0;logEvent("test_force_cars",{cars:n})},forcePlayerX:(x)=>{S.px=Math.max(0,Math.min(tw()-24,+x||0));logEvent("test_force_player",{px:S.px})},start:startRound,attack};
const standalone=standaloneMode();if(standalone){document.getElementById("fullscreenTip").style.display="none";document.getElementById("pwaNote").textContent="当前已在独立全屏模式运行。"}
setInterval(()=>{if(S.running)flushRemote("heartbeat")},10000);logEvent("boot",{...snap(),screen:[screen.width,screen.height]});setTimeout(()=>flushRemote("boot"),1200);draw();hud();
