function prevent(e){e.preventDefault();e.stopPropagation()}
function bindHold(id,dir){const el=document.getElementById(id);const down=e=>{prevent(e);S.move=dir;S.facing=dir;el.classList.add("active");logEvent("move_start",{dir,px:S.px})};const up=e=>{prevent(e);if(S.move===dir)S.move=0;el.classList.remove("active");logEvent("move_end",{dir,px:S.px})};["pointerdown","touchstart","mousedown"].forEach(n=>el.addEventListener(n,down,{passive:false}));["pointerup","pointercancel","pointerleave","touchend","touchcancel","mouseup"].forEach(n=>el.addEventListener(n,up,{passive:false}))}
function bindTap(id,fn){const el=document.getElementById(id);el.addEventListener("pointerdown",e=>{prevent(e);el.classList.add("active");fn()},{passive:false});el.addEventListener("pointerup",e=>{prevent(e);el.classList.remove("active")},{passive:false})}
bindHold("L",-1);bindHold("R",1);bindTap("attack",attack);bindTap("fix",repair);bindTap("layer",toggleLayer);
document.getElementById("start").onclick=startRun;document.getElementById("more").onclick=oneMore;document.getElementById("cash").onclick=cashOut;
document.getElementById("debugBtn").onclick=()=>{renderDebug();document.getElementById("debugPanel").style.display="flex"};document.getElementById("refreshDebug").onclick=renderDebug;document.getElementById("closeDebug").onclick=()=>document.getElementById("debugPanel").style.display="none";document.getElementById("reportDebug").onclick=()=>{const body=encodeURIComponent("BUILD "+BUILD+" SESSION "+SESSION+"\n\n```json\n"+JSON.stringify({snapshot:snap(),logs:LOGS.slice(-140)},null,2)+"\n```");location.href="https://github.com/lys20001205/m1ce/issues/new?title="+encodeURIComponent("ROUNDHOUSE V9 test "+SESSION)+"&body="+body};
["contextmenu","selectstart","dragstart","gesturestart"].forEach(n=>document.addEventListener(n,e=>e.preventDefault(),{passive:false}));
setInterval(()=>flushRemote("heartbeat"),10000);logEvent("boot",{standalone:standaloneMode(),inner:[innerWidth,innerHeight]});
window.__RH_DEBUG={snapshot:snap,logs:()=>LOGS,forceRoute:t=>{S.routeT=Math.max(0,Math.min(1,t));S.phase=phaseAt(S.routeT)},forceCars:n=>{while(S.cars.length<n){const type=S.cars.length%2?"battery":"cargo",d=carDefs[type],c={type,hp:d.hp,max:d.hp};if(type==="cargo")c.cargo=3;S.cars.push(c)}},forcePlayerX:x=>S.px=Math.max(0,Math.min(tw()-30,x))};
