function spawn(){let type="boarder",q=Math.random();if(S.round>=2&&q<.24)type="thief";else if(S.round>=3&&q>.84)type="clinger";const lane=type==="clinger"?"roof":"floor";S.enemies.push({type,lane,x:Math.random()<.5?0:Math.max(0,tw()-30),hp:type==="boarder"?2:3,atk:0,flash:0});logEvent("spawn",{enemy:type,lane,count:S.enemies.length})}
function damageEnemy(en,dmg,sourceX,knock=0){en.hp-=dmg;en.flash=1;en.x+=knock;addFloat(en.x,120,"-"+dmg,"#fff0b0");addSpark(en.x,130,"#ffd47c");hitShake(2)}
function attack(){if(!S.running||S.attackCd>0)return;logEvent("attack",{weapon:weaponName(),px:+S.px.toFixed(1),facing:S.facing,roof:S.roof});S.attackCd=weaponCooldown();const wl=weaponLevel(),lane=S.roof?"roof":"floor",r=weaponRange(),pose=playerPose(VIEW.base);if(wl<2){let best=null,bd=999;for(const en of S.enemies){if(en.lane!==lane)continue;const dx=(en.x-S.px)*S.facing;if(dx>=-8&&dx<r&&Math.abs(en.x-S.px)<bd){best=en;bd=Math.abs(en.x-S.px)}}S.effects.push({type:"swing",x:pose.handX,y:pose.handY,facing:S.facing,life:.24,maxLife:.24,heavy:wl===1});if(best){damageEnemy(best,weaponDamage(),S.px,S.facing*(wl===1?30:20));if(best.hp<=0){S.money+=40*S.mult;addFloat(best.x,pose.handY-18,"+$40","#7be093")}}else setEvent("近战没打到：靠近敌人再挥击。");hitShake(wl===1?1.3:.8)}else{const speed=wl===3?540:430,x=pose.handX+S.facing*8,y=pose.handY;S.projectiles.push({owner:"player",lane,x,y,vx:S.facing*speed,life:r/speed,damage:weaponDamage()});addSpark(x,y,"#ffe49a");S.effects.push({type:"muzzle",x,y,facing:S.facing,life:.08});hitShake(.7);logEvent("projectile_spawn",{x:+x.toFixed(1),y:+y.toFixed(1),handX:+pose.handX.toFixed(1),handY:+pose.handY.toFixed(1)})}}
function updateProjectiles(dt){for(const p of S.projectiles){p.x+=p.vx*dt;p.life-=dt;for(const en of S.enemies){if(en.hp<=0||en.lane!==p.lane)continue;if(Math.abs(en.x-p.x)<12){damageEnemy(en,p.damage,p.x,Math.sign(p.vx)*8);p.life=0;if(en.hp<=0){S.money+=(p.owner==="turret"?25:40)*S.mult;addFloat(en.x,108,p.owner==="turret"?"+$25":"+$40","#7be093")}break}}}S.projectiles=S.projectiles.filter(p=>p.life>0);S.enemies=S.enemies.filter(e=>e.hp>0)}
function turretStep(dt,base){S.turretCd-=dt;if(S.turretCd>0)return;const turrets=S.cars.map((c,i)=>({c,i})).filter(o=>o.c.type==="turret"&&o.c.hp>0);if(!turrets.length)return;for(const o of turrets){const tx=o.i*150+78;let target=null,dist=999;for(const en of S.enemies){const d=Math.abs(en.x-tx);if(d<=S.turretRange&&d<dist){target=en;dist=d}}if(target){S.turretCd=1.05;const lane=target.lane;const ty=laneY(lane,VIEW.base)+16;S.projectiles.push({owner:"turret",lane,x:tx,y:ty,vx:Math.sign(target.x-tx||1)*360,life:S.turretRange/360,damage:1});addSpark(tx,ty,"#8dccff");return}}}
function ai(dt){S.enemies.forEach(en=>{en.flash=Math.max(0,en.flash-dt*4);let ti=carIndexAt(S.px),tx=S.px;if(en.type==="thief"){let found=-1;for(let i=S.cars.length-1;i>=0;i--)if(S.cars[i].type==="cargo"&&(S.cars[i].cargo||0)>0){found=i;break}if(found>=0){ti=found;tx=ti*150+78}}if(en.type==="clinger"){ti=Math.max(1,Math.min(S.cars.length-1,carIndexAt(en.x)));tx=ti*150+76}const sp=en.type==="thief"?46:30;if(Math.abs(en.x-tx)>12)en.x+=Math.sign(tx-en.x)*sp*dt;else{en.atk+=dt;if(en.atk>1){en.atk=0;if(en.type==="thief"){const c=S.cars[ti];if(c&&c.type==="cargo"&&(c.cargo||0)>0){c.cargo--;S.money=Math.max(0,S.money-250*S.mult);setEvent("THIEF 抢走一箱货物！");addFloat(en.x,120,"-$250","#ffb0b0");hitShake(2.5)}}else{const c=S.cars[ti];if(c){const dmg=en.type==="clinger"?7:4;c.hp=Math.max(0,c.hp-dmg);addFloat(ti*150+48,120,"-"+dmg,"#ffb0b0");hitShake(en.type==="clinger"?4:2.5);if(ti===0&&c.hp<=0)lose("ENGINE DESTROYED");else if(en.type==="clinger")setEvent("CLINGER 正在撕裂车体！")}}}}})}
function updateEffects(dt){for(const f of S.effects){f.life-=dt;if(f.type==="float")f.y-=28*dt;else if(f.type==="spark"){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vy+=180*dt}}S.effects=S.effects.filter(f=>f.life>0)}
function update(dt){if(!S.running){updateEffects(dt);return}S.time-=dt;S.spawn+=dt;S.attackCd=Math.max(0,S.attackCd-dt);if(S.move){S.facing=S.move;S.px=Math.max(0,Math.min(tw()-24,S.px+S.move*120*dt))}if(S.spawn>Math.max(.9,3.15-S.round*.18)){S.spawn=0;spawn()}ai(dt);turretStep(dt);updateProjectiles(dt);updateEffects(dt);S.enemies=S.enemies.filter(e=>e.hp>0&&e.x>-80&&e.x<tw()+80);if(S.time<=0)finish()}
function loop(ts){const dt=Math.min(.05,(ts-(S.last||ts))/1000);S.last=ts;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function startRound(){logEvent("start_round",snap());S.running=true;S.time=45+Math.min(24,(S.round-1)*3);S.spawn=0;S.last=0;document.getElementById("modal").style.display="none";setEvent("Round "+S.round+"："+weaponName()+" · "+(weaponLevel()<2?"先靠近再攻击。":"黄线就是你的最大射程。"))}
function finish(){logEvent("finish_round",snap());S.running=false;S.money+=Math.round((900+S.round*500)*S.mult);showRoundhouse()}
function hideMetaPanels(){document.getElementById("roundUi").style.display="none";document.getElementById("garageUi").style.display="none";document.getElementById("cash").style.display="none";document.getElementById("more").style.display="none";document.getElementById("garageBtn").style.display="none";document.getElementById("newRun").style.display="none";document.getElementById("start").style.display="none"}
function showRoundhouse(){document.getElementById("modal").style.display="flex";hideMetaPanels();document.getElementById("mt").textContent="ROUND COMPLETE";document.getElementById("ms").textContent="继续会把当前未兑现收益继续押上；Cash Out 会存入永久 BANK。";document.getElementById("intro").style.display="none";document.getElementById("roundUi").style.display="block";document.getElementById("cash").style.display="block";document.getElementById("more").style.display="block";document.getElementById("rm").textContent=cash(S.money);document.getElementById("rx").textContent="×"+(S.mult*1.28).toFixed(2);document.getElementById("rw").textContent=nextWeaponText();buildChoices()}
function availableCarPool(){const pool=["battery","workshop","cargo"];if(META.unlocks.passenger)pool.push("passenger");const hasTurret=S.cars.some(c=>c.type==="turret");if(S.round>=3&&META.unlocks.turret&&!hasTurret)pool.push("turret");return pool}
function buildChoices(){const root=document.getElementById("choices");root.innerHTML="";const pool=availableCarPool();const a=(S.round-1+S.choiceOffset)%pool.length,p=[pool[a],pool[(a+1)%pool.length]];if(!p.includes(S.selected))S.selected=p[0];for(const type of p){const d=document.createElement("div");d.className="choice"+(S.selected===type?" sel":"");d.innerHTML="<b>"+carDefs[type][0]+"</b> — "+hints[type];d.addEventListener("click",()=>{S.selected=type;buildChoices()});root.appendChild(d)}const rr=document.getElementById("reroll");rr.style.display="block";rr.disabled=META.rerollTokens<=0;rr.textContent="REROLL · "+META.rerollTokens+" token"+(META.rerollTokens===1?"":"s")}
function rerollChoices(){if(META.rerollTokens<=0)return;META.rerollTokens--;S.choiceOffset++;saveMeta();logEvent("reroll",{remaining:META.rerollTokens,round:S.round});buildChoices()}
function oneMore(){logEvent("one_more_round",{selected:S.selected,...snap()});S.round++;S.mult*=1.28;S.choiceOffset=0;const type=S.selected,def=carDefs[type],c={type,hp:def[1],max:def[1]};if(type==="cargo")c.cargo=4;S.cars.push(c);S.px=52;S.enemies=[];S.projectiles=[];S.roof=false;document.getElementById("mt").textContent="ROUNDHOUSE";document.getElementById("ms").textContent=carDefs[type][0]+" 已接入。装备升级为 "+weaponName()+"。";hideMetaPanels();const st=document.getElementById("start");st.style.display="block";st.textContent="START ROUND "+S.round;setEvent("准备开始 Round "+S.round+" · "+weaponName())}
const SHOP=[
  {id:"reroll",name:"Reroll Token",cost:3000,desc:"消耗品。下一局在 Roundhouse 可以重抽一次车厢二选一。"},
  {id:"passenger",name:"Passenger Contracts",cost:15000,desc:"永久许可证。之后 Passenger Car 才会进入车厢候选。"},
  {id:"turret",name:"Turret Permit",cost:45000,desc:"永久许可证。Round 3+ 才可能出现 Turret Car；仍然只有局部射程。"}
];
function ownedShopItem(id){if(id==="reroll")return META.rerollTokens>=3;if(id==="passenger")return META.unlocks.passenger;if(id==="turret")return META.unlocks.turret;return false}
function garagePurchase(id){const item=SHOP.find(x=>x.id===id);if(!item)return;if(id==="reroll"&&META.rerollTokens>=3)return;if(id!=="reroll"&&ownedShopItem(id))return;if(META.bank<item.cost){setEvent("BANK 不足：还差 "+cash(item.cost-META.bank));return}META.bank-=item.cost;if(id==="reroll")META.rerollTokens++;else META.unlocks[id]=true;saveMeta();logEvent("garage_purchase",{item:id,amount:item.cost,bank:META.bank});renderGarage("PURCHASED · "+item.name)}
function renderGarage(status=""){document.getElementById("bankValue").textContent=cash(META.bank);const root=document.getElementById("garageShop");root.innerHTML="";for(const item of SHOP){const owned=ownedShopItem(item.id),can=META.bank>=item.cost&&!owned;const row=document.createElement("div");row.className="shopRow";const left=document.createElement("div");left.className="shopCopy";left.innerHTML="<b>"+item.name+"</b><span>"+item.desc+"</span>";const btn=document.createElement("button");btn.type="button";btn.className="shopBtn";btn.disabled=!can;btn.textContent=owned?(item.id==="reroll"?"MAX 3":"OWNED"):cash(item.cost);btn.addEventListener("click",()=>garagePurchase(item.id));row.append(left,btn);root.appendChild(row)}if(status)setEvent(status)}
function showGarage(deposit=0){document.getElementById("modal").style.display="flex";hideMetaPanels();document.getElementById("mt").textContent="ROUNDHOUSE GARAGE";document.getElementById("ms").textContent=deposit>0?("本局已兑现 "+cash(deposit)+"。BANK 不会在失败时丢失。"):("BANKED CREDITS 可用于许可证和下一局的选择工具。");document.getElementById("intro").style.display="none";document.getElementById("garageUi").style.display="block";document.getElementById("newRun").style.display="block";renderGarage()}
function cashOutRun(){const deposit=Math.max(0,Math.floor(S.money));META.bank+=deposit;saveMeta();logEvent("cash_out",{amount:deposit,bank:META.bank,...snap()});S.running=false;showGarage(deposit)}
function resetRun(){S.round=1;S.money=1000;S.mult=1;S.time=45;S.running=false;S.roof=false;S.px=52;S.facing=1;S.enemies=[];S.cars=[{type:"engine",hp:160,max:160},{type:"cargo",hp:100,max:100,cargo:3}];S.spawn=0;S.last=0;S.selected="battery";S.choiceOffset=0;S.move=0;S.effects=[];S.shake=0;S.attackCd=0;S.projectiles=[];S.turretCd=0;S.cameraX=0;logEvent("new_run",{bank:META.bank,rerolls:META.rerollTokens,unlocks:{...META.unlocks}});document.getElementById("modal").style.display="flex";hideMetaPanels();document.getElementById("mt").textContent="ROUNDHOUSE";document.getElementById("ms").textContent="新一局从 WRENCH 开始。BANKED CREDITS 已保留。";document.getElementById("intro").style.display="flex";const st=document.getElementById("start");st.style.display="block";st.textContent="START RUN";setEvent("新一局准备完成 · BANK "+cash(META.bank));hud()}
function lose(reason){logEvent("run_over",{reason,...snap()});S.running=false;document.getElementById("modal").style.display="flex";hideMetaPanels();document.getElementById("mt").textContent="RUN OVER";document.getElementById("ms").innerHTML=reason+"<br>失去未兑现收益 "+cash(S.money)+"<br>BANK 保留："+cash(META.bank);document.getElementById("intro").style.display="none";document.getElementById("garageBtn").style.display="block"}
function fix(){if(!S.running)return;logEvent("repair_press",{px:+S.px.toFixed(1),car:carIndexAt(S.px)});const i=carIndexAt(S.px),c=S.cars[i],bonus=S.cars.some(x=>x.type==="workshop"&&x.hp>0)?18:10;c.hp=Math.min(c.max,c.hp+bonus);addFloat(i*150+55,105,"+"+bonus,"#94f1ad");setEvent("修理 CAR "+(i+1)+" +"+bonus+" HP")}
