import test from 'node:test';import assert from 'node:assert/strict';import {AudioCues,AUDIO_CUES} from '../src/audio.js';
function fixture(){
 const events=[],calls=[];const param=(value=0)=>({value,setValueAtTime(v){this.value=v;},setTargetAtTime(v){this.value=v;},linearRampToValueAtTime(v){this.value=v;},exponentialRampToValueAtTime(v){this.value=v;},cancelScheduledValues(){}});
 const node=()=>({gain:param(),frequency:param(),threshold:param(),knee:param(),ratio:param(),connections:[],connect(n){this.connections.push(n);},disconnect(){},start(){},stop(t){if(t===undefined)this.onended?.();}});
 const c={state:'suspended',currentTime:0,sampleRate:44100,destination:node(),createGain:node,createOscillator:node,createBiquadFilter:node,createDynamicsCompressor:node,createBufferSource:node,
 createBuffer:(ch,count)=>({getChannelData:()=>new Float32Array(count)}),createAnalyser:()=>({...node(),fftSize:1024,getFloatTimeDomainData:a=>a.fill(audio.master.gain.value?.01:0)}),
 resume(){calls.push('resume');this.state='running';return Promise.resolve();}};
 let creates=0;const audio=new AudioCues({contextFactory:()=>{creates++;return c;},hidden:()=>false,emit:(type,data)=>events.push({type,...data})});
 const g={status:'running',paused:false,engineState:'normal',speedMode:'CRUISE',elapsed:5,phase:'yard'};return{audio,c,events,calls,g,creates:()=>creates};
}
test('Audio creates nothing until a gesture, and resume is requested synchronously before unlock returns',()=>{const f=fixture();assert.equal(f.creates(),0);f.audio.unlock('start');f.calls.push('returned');assert.deepEqual(f.calls,['resume','returned']);assert.equal(f.creates(),1);f.audio.unlock('start');assert.equal(f.creates(),1);assert.equal(f.audio.resumeRequested,2);});
test('Music Ambience and SFX all connect to Master; Mute changes Master only and restores one',()=>{const {audio}=fixture();audio.unlock();for(const bus of Object.values(audio.buses))assert(bus.connections.includes(audio.master));audio.setEnabled(false);assert.equal(audio.master.gain.value,0);assert.equal(audio.snapshot().muted,true);audio.setEnabled(true);assert.equal(audio.master.gain.value,1);assert.equal(audio.snapshot().muted,false);});
test('every required synthesized cue has a valid oscillator envelope and real voice scheduling',()=>{const {audio}=fixture();audio.unlock();for(const name of Object.keys(AUDIO_CUES)){assert(audio.play(name),name);assert.equal(audio.lastSfx,name);for(const v of [...audio.voices])v.o.stop();}assert.equal(audio.voices.size,0);assert(!audio.play('unknown'));});
test('production events select six different weapon cues and all train/life cues',()=>{const {audio}=fixture();audio.unlock();for(const weapon of ['wrench','knife','axe','handgun','smg','rifle']){audio.event('attack',{weapon});assert.equal(audio.lastSfx,weapon);}for(const [event,cue,data] of [['depart','turntable'],['engine_recovered','engine_restart'],['hazard_warning','tunnel_enter',{hazard:'tunnel'}],['hazard_warning','crane_alarm',{hazard:'crane'}],['train_lost','train_lost'],['respawn_complete','respawn'],['scrap_gain','scrap_gain']]){audio.event(event,data);assert.equal(audio.lastSfx,cue);}});
test('voice and pending queues are bounded',()=>{const {audio,c}=fixture();audio.unlock();for(let i=0;i<100;i++)audio.play('smg');assert.equal(audio.voices.size,24);audio.silence();assert.equal(audio.voices.size,0);audio.quiet=false;c.state='suspended';for(let i=0;i<20;i++)audio.play('wrench');assert.equal(audio.pending.length,6);});
test('engine speed and rail cadence use AudioContext wall time, never simulation multiplier or elapsed',()=>{const {audio,c,g}=fixture();audio.unlock();audio.update(g);assert.equal(audio.engineLoop,'cruise');const hz=audio.engineOsc.frequency.value,rail=audio.nextRail;g.elapsed*=4;g.timeScale=4;audio.update(g);assert.equal(audio.engineOsc.frequency.value,hz);assert.equal(audio.nextRail,rail);g.speedMode='FAST';audio.update(g);assert.equal(audio.engineLoop,'fast');assert(audio.engineOsc.frequency.value>hz);g.speedMode='STOP';audio.update(g);assert.equal(audio.engineLoop,'idle');c.currentTime=10;audio.update(g);assert.equal(audio.nextRail,rail);});
test('first sound is emitted only from nonzero analyser output, never merely resume or trigger',()=>{const {audio,g,events}=fixture();audio.unlock();audio.play('test');assert(!events.some(e=>e.type==='audio_first_sound'));audio.setEnabled(false);audio.update(g);assert(!audio.firstSound);audio.setEnabled(true);audio.update(g);audio.update(g);assert.equal(events.filter(e=>e.type==='audio_first_sound').length,1);});
test('lifecycle silence never changes user mute preference and restore requests resume again when suspended',()=>{const {audio,c}=fixture();audio.unlock();audio.silence();assert.equal(audio.enabled,true);assert.equal(audio.master.gain.value,1);c.state='suspended';audio.restore('pageshow');assert.equal(audio.quiet,false);assert.equal(audio.resumeRequested,2);assert.equal(audio.context.state,'running');});
