import test from 'node:test';import assert from 'node:assert/strict';
import {Game,car} from '../src/sim.js';import {V11} from '../src/balance.js';
const tick=(g,t,input={})=>{for(let left=t;left>1e-8;left-=.025)g.step(Math.min(.025,left),input);};
const near=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function run(){const events=[];const g=new Game({bank:5000,emit:(type,data)=>events.push({type,...data})});g.chooseRoute('freight');g.chooseCar('cargo');g.start();g.elapsed=3;g.t=.1;g.phase='yard';return {g,events};}
function arm(g,scrap=200){g.scrap=scrap;g.player.x=V11.armoryX;assert(g.interact());}
function upgrades(g,range=0){arm(g);assert(g.buyWeapon('melee'));assert(g.buyWeapon('melee'));for(let i=0;i<range;i++)assert(g.buyWeapon('ranged'));}
function kill(g,type='boarder'){const e=g.spawn(type,8,false);assert(e);g.hitEnemy(e,10000,1,'axe');return e;}
test('kills grant immediate per-type Scrap once and never deposit money or Bank',()=>{for(const type of Object.keys(V11.enemies)){const {g,events}=run();const e=kill(g,type);assert.equal(g.scrap,V11.enemies[type].scrap);g.hitEnemy(e,10000);assert.equal(g.scrap,V11.enemies[type].scrap);assert.equal(g.money,1000);assert.equal(g.bank,5000);assert(g.effects.some(f=>f.type==='scrap'&&f.text===`+${g.scrap} SCRAP`));assert.equal(events.filter(x=>x.type==='scrap_gain').length,1);}});
test('Armory enforces exact sequential costs; T3 unlocks purchasing, never a free ranged gun',()=>{const {g,events}=run();arm(g,106);assert(!g.buyWeapon('ranged'));assert(g.buyWeapon('melee'));assert.equal(g.melee.id,'knife');assert.equal(g.scrap,96);assert(g.buyWeapon('melee'));assert.equal(g.melee.id,'axe');assert.equal(g.combatTier,3);assert.equal(g.ranged,null);assert.equal(g.scrap,76);assert(g.buyWeapon('ranged'));assert.equal(g.ranged.id,'handgun');assert(g.buyWeapon('ranged'));assert.equal(g.ranged.id,'smg');assert(g.buyWeapon('ranged'));assert.equal(g.ranged.id,'rifle');assert.equal(g.scrap,0);assert(!g.buyWeapon('ranged'));assert(!g.buyWeapon('melee'));assert.equal(events.filter(e=>e.type==='combat_tier_unlock').length,1);assert.equal(events.filter(e=>e.type==='ranged_unlock').length,1);});
test('cannot buy remotely, while dead, without funds or without an open Armory',()=>{const {g}=run();g.scrap=200;assert(!g.buyWeapon('melee'));arm(g,9);assert(!g.buyWeapon('melee'));assert.equal(g.scrap,9);g.scrap=200;g.player.x=6;assert(!g.buyWeapon('melee'));g.player.x=1.7;g.pause(true);assert(!g.buyWeapon('melee'));g.pause(false);g.killPlayer();assert(!g.buyWeapon('melee'));assert.equal(g.meleeTier,1);assert.equal(g.scrap,200);});
test('Armory never pauses route or enemies and closes on moving away or taking damage',()=>{const {g}=run();arm(g);const e=g.spawn('boarder',4,false);e.climb=0;const start=g.t;tick(g,.4);assert(g.t>start);assert(e.x<4);assert(g.armoryOpen);g.hurt(1,'boarder');assert(!g.armoryOpen);tick(g,.5);g.player.x=1.7;assert(g.openArmory());tick(g,.8,{move:1});assert(!g.armoryOpen);});
test('dual melee and ranged actions fire together with independent cooldowns and SSOT stats',()=>{const {g}=run();upgrades(g,3);g.player.x=3;g.armoryOpen=false;assert(g.attack());assert(g.rangedAttack());assert(g.player.swing>0);assert.equal(g.projectiles.length,1);assert.equal(g.player.cooldown,V11.weapons.axe.cooldown);assert.equal(g.player.rangedCooldown,V11.weapons.rifle.cooldown);assert.equal(g.projectiles[0].damage,V11.weapons.rifle.damage);assert.equal(g.projectiles[0].range,V11.weapons.rifle.range);assert.equal(g.player.meleeAttack.damage,V11.weapons.axe.damage);assert(!g.rangedAttack());});
test('knife is genuinely faster than Wrench and Axe; melee damage uses active-frame timing',()=>{for(const tier of [1,2,3]){const {g}=run();arm(g);for(let i=1;i<tier;i++)g.buyWeapon('melee');g.player.x=3;const e=g.spawn('boarder',4,false);e.climb=0;const spec=g.meleeStats;g.attack();tick(g,spec.active-.025);assert.equal(e.hp,45);tick(g,.025);assert.equal(e.hp,Math.max(0,45-spec.damage));assert.equal(spec,V11.weapons[g.melee.id]);}assert(V11.weapons.knife.cooldown<V11.weapons.wrench.cooldown);assert(V11.weapons.axe.cooldown>V11.weapons.wrench.cooldown);});
test('projectiles retain their firing direction, weapon damage and range after movement or upgrades',()=>{const {g}=run();upgrades(g,1);g.player.x=3;g.rangedAttack();const b=g.projectiles[0];g.player.face=-1;g.player.x=1.7;g.openArmory();g.buyWeapon('ranged');g.buyWeapon('ranged');assert.equal(b.weapon,'handgun');assert.equal(b.damage,23);assert.equal(b.range,12);const old=b.x;tick(g,.025);assert(b.x>old);});
test('one stopped encounter pays six full rewards then reduced reinforcements without changing cap',()=>{const {g}=run();g.player.x=5.8;g.setSpeed('STOP');const cap=g.director.snapshot(g).cap;for(let i=0;i<6;i++)kill(g,'saboteur');assert.equal(g.scrap,24);kill(g,'saboteur');assert.equal(g.scrap,25);assert.equal(g.director.snapshot(g).cap,cap);assert.equal(g.director.snapshot(g).pressure,1.8);});
test('speed toggling or accelerating before killing cannot reset a stop spawn reward quota',()=>{const {g}=run();g.player.x=5.8;g.setSpeed('STOP');for(let i=0;i<6;i++)kill(g,'bruiser');const e=g.spawn('bruiser',8,false);g.setSpeed('CRUISE');g.hitEnemy(e,10000,1,'axe');assert.equal(g.scrap,37);g.setSpeed('STOP');kill(g,'bruiser');assert.equal(g.scrap,38);});
test('each Depot has its own quota, independent of STOP/SLOW/CRUISE toggles',()=>{const {g}=run();g.t=.26;for(let i=0;i<7;i++)kill(g,'boarder');assert.equal(g.scrap,13);g.t=.66;kill(g,'boarder');assert.equal(g.scrap,15);assert.equal(g.rewardEncounters.size,2);});
test('thief escape does not count as a player kill or give Scrap',()=>{const {g}=run();g.createCargo(450,'stored',{carIndex:1,secured:true});g.player.x=12.4;const e=g.spawn('thief',12.4,false);e.climb=0;tick(g,3);assert.equal(g.scrap,0);assert.equal(g.totalKills,0);assert.equal(g.total.cargoLost,450);});
test('normal death and rounds preserve both weapons and Scrap; Cash Out and failure clear only run combat',()=>{for(const ending of ['cashout','fail']){const {g}=run();upgrades(g,2);const scrap=g.scrap;g.killPlayer();tick(g,5);assert.equal(g.scrap,scrap);assert.equal(g.meleeTier,3);assert.equal(g.rangedTier,2);g.finish();tick(g,4);if(ending==='cashout'){assert(g.cashout());assert(g.bank>5000);}else{assert(g.more());assert.equal(g.scrap,scrap);assert.equal(g.rangedTier,2);g.chooseRoute('freight');g.chooseCar('cargo');g.start();g.fail();assert.equal(g.bank,5000);}assert.equal(g.scrap,0);assert.equal(g.meleeTier,1);assert.equal(g.rangedTier,0);}});
test('firing muzzle is a stable per-weapon local coordinate in both directions',()=>{const {g}=run();upgrades(g);for(let tier=1;tier<=3;tier++){assert(g.buyWeapon('ranged'));for(const face of [-1,1]){g.player.face=face;const m=g.muzzle();near(m.x,g.player.x+face*(V11.rig.armX+g.rangedStats.muzzle)*V11.rig.scale);near(m.y,g.player.y+V11.rig.armY*V11.rig.scale);near(m.z,.65+face*V11.rig.armZ*V11.rig.scale);}}});
