import test from 'node:test';import assert from 'node:assert/strict';
import {Game,car,ROOF,FLOOR,stationX} from '../src/sim.js';import {V11,capFor} from '../src/balance.js';
const tick=(g,t,input={})=>{for(let left=t;left>1e-8;left-=.025)g.step(Math.min(.025,left),input);};
function make(route='freight',round=1){const events=[];const g=new Game({seed:314159,emit:(type,data)=>events.push({type,...data})});g.chooseRoute(route);g.chooseCar('cargo');g.start();g.round=round;g.elapsed=3;g.t=.1;g.phase='yard';g.player.x=3;return {g,events};}
test('boarder pursues Player, winds up, then damages Player instead of a healthy system',()=>{const {g,events}=make();const e=g.spawn('boarder',6,false);e.climb=0;tick(g,1.1);assert(e.x<6);assert.equal(g.cars[0].hp,180);tick(g,1);assert(g.player.hp<100);assert(events.some(x=>x.type==='enemy_windup'&&x.target==='player'));});
test('boarder changing lanes physically walks to and climbs a ladder before it can hit',()=>{const {g}=make();g.player.roof=true;g.player.y=ROOF;const e=g.spawn('boarder',4.3,false);e.climb=0;tick(g,.5);assert.equal(e.state,'climb_ladder');assert(e.y>FLOOR&&e.y<ROOF);assert.equal(g.player.hp,100);tick(g,1);assert(e.roof);assert.equal(e.y,ROOF);});
test('clinger attaches at the side, climbs vertically, then establishes roof pressure',()=>{const {g}=make();const e=g.spawn('clinger',8);assert.equal(e.state,'attach');assert(e.z>1.5);assert(e.y<FLOOR);tick(g,.6);assert.equal(e.state,'attach');tick(g,.5);assert.equal(e.state,'climb');assert(e.y>FLOOR&&e.y<ROOF);tick(g,.9);assert.equal(e.y,ROOF);assert(e.roof);assert.equal(e.z,.65);assert.equal(g.player.hp,100);});
test('thief prioritizes a crate over a nearby Player; debit occurs only at escape',()=>{const {g}=make();g.player.x=12.4;const c=g.createCargo(450,'stored',{carIndex:1,secured:true}),e=g.spawn('thief',12.4,false);e.climb=0;tick(g,.8);assert.equal(e.carry,c.id);assert.equal(c.location,'thief');assert.equal(g.player.hp,100);assert.equal(g.money,1000);tick(g,2);assert.equal(c.location,'lost');assert.equal(g.money,550);assert.equal(g.total.cargoLost,450);});
test('saboteur walks to Battery then Workshop then Engine, telegraphs system damage and ignores Player',()=>{const {g,events}=make('industrial',3);g.cars.push(car('battery'),car('workshop'));const i=2;g.player.x=stationX(i);const e=g.spawn('saboteur',stationX(i),false);e.climb=0;tick(g,1);assert.equal(e.targetCar,2);assert.equal(e.state,'system_windup');assert.equal(g.cars[2].hp,100);assert.equal(g.player.hp,100);tick(g,.4);assert.equal(g.cars[2].hp,80);assert.equal(g.player.hp,100);g.damageCar(2,100);tick(g,.1);assert.equal(e.targetCar,3);g.damageCar(3,120);tick(g,.1);assert.equal(e.targetCar,0);assert(events.some(x=>x.type==='enemy_windup'&&x.target==='system'&&x.enemy_type==='saboteur'));});
test('bruiser has long interruptible heavy windup, low speed and actual knockback/armor resistance',()=>{const {g}=make('tunnel',3);const e=g.spawn('bruiser',3.8,false);e.climb=0;tick(g,1);assert.equal(g.player.hp,100);assert.equal(e.state,'heavy_windup');const x=e.x,wind=e.wind;g.hitEnemy(e,22,1,'wrench');assert(e.hp>130&&e.hp<140);assert(e.x-x<.1);assert.equal(e.wind,wind);tick(g,.7);assert(g.player.hp<100);const h=e.hp;g.hitEnemy(e,54,1,'axe');assert.equal(e.hp,h-54);assert.equal(e.wind,0);});
test('Bruiser swing can miss when Player leaves its reach during the windup',()=>{const {g}=make('tunnel',3);const e=g.spawn('bruiser',3.5,false);e.climb=0;tick(g,1);tick(g,.6,{move:1});assert.equal(g.player.hp,100);assert.equal(e.wind,0);assert(e.recovery>0);});
test('Round one really spawns the route-specific special, with no late-round-only gate',()=>{for(const [route,special] of [['industrial','saboteur'],['freight','thief'],['tunnel','clinger']]){const seen=new Set();for(let seed=1;seed<=120;seed++){const {g}=make(route);g.seed=seed*997;tick(g,10);for(const e of g.enemies)seen.add(e.type);}assert(seen.has('boarder'));assert(seen.has(special),route);assert.equal(seen.size,2);}});
test('Round two opens the four-role pool; Round three admits Bruiser; caps stop at eight',()=>{const {g}=make();g.round=2;assert.deepEqual(new Set(g.director.pool(g)),new Set(['boarder','clinger','thief','saboteur']));g.round=3;assert(g.director.pool(g).includes('bruiser'));assert.deepEqual([1,2,3,4,5,6,7,8].map(capFor),[3,4,5,6,7,8,8,8]);});
test('route weights and extra cargo cars affect type selection without changing threat admission',()=>{const {g}=make('freight',3);let w=g.director.weights(g);assert(w.thief>w.saboteur);g.cars.push(car('cargo'));assert(g.director.weights(g).thief>w.thief);const cap=g.director.snapshot(g).cap;g.route='industrial';w=g.director.weights(g);assert(w.saboteur>w.bruiser);g.route='tunnel';w=g.director.weights(g);assert(w.bruiser>w.thief);assert.equal(g.director.snapshot(g).cap,cap);});
test('STOP has higher actual admitted spawn cadence while respecting the same cap',()=>{let stopped,cruise;for(const mode of ['STOP','CRUISE']){const {g}=make();g.player.x=5.8;g.setSpeed(mode);tick(g,3);if(mode==='STOP')stopped=g;else cruise=g;}assert(stopped.enemies.length>cruise.enemies.length);assert(stopped.director.load(stopped)<=stopped.director.effectiveCap(stopped));});
test('Industrial faults use their actual route marker and never appear on other routes',()=>{for(const route of ['industrial','freight','tunnel']){const {g}=make(route,3);g.t=.151;tick(g,.05);assert.equal(!!g.director.fault,route==='industrial');}});
test('depot layer cannot hit a roof enemy through the depth separation',()=>{const {g}=make();g.player.x=5.8;g.setSpeed('STOP');g.t=.26;g.player.x=12.45;g.layer();g.interact();const e=g.spawn('boarder',12.45,true);e.climb=0;g.attack();tick(g,.25);assert.equal(e.hp,45);});

test('telemetry envelope preserves event name and sequence against colliding payload keys',async()=>{const {Telemetry}=await import('../src/telemetry.js');const logger={seq:0,events:[],errors:0,flush(){},persist(){}};Telemetry.prototype.log.call(logger,'enemy_spawn',{type:'clinger',seq:99,ms:-1,enemy_type:'clinger'});assert.equal(logger.events[0].type,'enemy_spawn');assert.equal(logger.events[0].seq,1);assert(logger.events[0].ms>=0);assert.equal(logger.events[0].enemy_type,'clinger');});
