import test from 'node:test';import assert from 'node:assert/strict';
import {Game} from '../src/sim.js';import {SaveStore,cleanSave} from '../src/save.js';
import {cargoNotice} from '../src/playability_ui.js';
const tick=(g,t,input={})=>{for(let left=t;left>1e-8;left-=.025)g.step(Math.min(.025,left),input);};
function dock(seed=1){const events=[],g=new Game({seed,emit:(type,data)=>events.push({time:g.elapsed,type,...data})});g.chooseRoute('freight');g.chooseCar('cargo');g.start();g.elapsed=40;g.t=.26;g.phase='yard';g.speedMode='STOP';g.player.x=12.45;g.director.rest=999;return {g,events};}
function collect(g,x=1){assert(g.interact());assert.equal(g.playerLayer,'DEPOT');tick(g,Math.abs(x)/5.1,{move:Math.sign(x)});assert(g.heldCargo);if(Math.abs(g.player.depotX)>2.5)tick(g,Math.abs(g.player.depotX)/g.carrySpeed,{move:-Math.sign(x)});assert(g.interact());assert.equal(g.playerLayer,'INTERIOR');}
test('two-crate input loop gives a usable first shipment window across seeds',()=>{for(const seed of [1,29,314159,87234]){const {g}=dock(seed);collect(g);const first=g.cargoCrates.find(c=>c.location==='stored'),deadline=first.protectedUntil;collect(g,-3);assert.equal(g.storedCargo,2);assert(g.elapsed<deadline);assert.equal(g.money,1900);assert.equal(g.bank,0);assert.equal(g.cargoLedger.loaded,900);}});
test('same crate reload, station re-entry and third crate cannot refresh first protection',()=>{const {g}=dock();collect(g);const c=g.cargoCrates.find(c=>c.location==='stored'),deadline=c.protectedUntil;g.player.x=15;assert(g.pickupCargo(c));tick(g,1);assert(g.loadCargo());assert.equal(c.protectedUntil,deadline);assert.equal(g.money,1450);g.player.x=12.45;collect(g,-3);collect(g,5);assert.equal(g.storedCargo,3);assert.equal(g.cargoCrates.filter(c=>c.protectedUntil).length,1);assert(g.interact());g.player.depotX=9;g.syncDepotPlayer();const remaining=g.cargoCrates.find(c=>c.location==='depot'&&c.x===9);assert(!g.pickupCargo(remaining));assert.equal(remaining.location,'depot');});
test('theft telegraph and escape hold provide a real rescue path, then loss debits once',()=>{const {g,events}=dock();collect(g);tick(g,18.05);g.director.rest=999;g.player.x=12.45;const c=g.cargoCrates.find(c=>c.location==='stored'),e=g.spawn('thief',12.45,false);e.climb=0;tick(g,2.95);assert(!e.carry);assert(events.some(e=>e.type==='thief_targeting'));tick(g,.05);assert.equal(c.location,'thief');assert.equal(g.money,1450);const start=e.x;tick(g,5.9);assert.equal(e.x,start);assert.equal(g.cargoLedger.atRisk,450);assert.equal(g.cargoLedger.loaded,0);tick(g,2);assert.equal(c.location,'lost');assert.equal(g.money,1000);assert.equal(g.bank,0);assert.equal(g.total.cargoLost,450);tick(g,3);assert.equal(g.total.cargoLost,450);});
test('recovery retains value once and cannot recreate the shipment grace',()=>{const {g}=dock();collect(g);tick(g,18.05);const c=g.cargoCrates.find(c=>c.location==='stored'),e=g.spawn('thief',12.45,false);e.climb=0;tick(g,3);g.hitEnemy(e,99);g.hitEnemy(e,99);assert.equal(g.cargoLedger.atRisk,0);assert.equal(g.money,1450);assert.equal(g.total.cargoSaved,450);assert(c.protectedUntil<g.elapsed);});
test('old save migrates career safely; permanent purchases roundtrip into real next-run behavior',()=>{const map=new Map([['roundhouse_save_v11',JSON.stringify({version:11,bank:3000,prep:{reroll:1}})]]),backend={getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v)};const store=new SaveStore({backend}),old=store.read();assert.deepEqual(old.career,{boots:0,hull:0,kit:0});const g=new Game(old);for(const id of ['boots','hull','kit'])assert(g.buyCareer(id));assert(store.write(g));const next=new Game(store.read());next.chooseRoute('freight');next.chooseCar('cargo');next.start();assert.equal(next.cars[0].max,210);assert(Math.abs(next.carrySpeed-3.6)<1e-8);assert.equal(next.ranged.id,'handgun');assert.equal(next.scrap,6);assert(next.weaponInventory.ranged.includes('handgun'));assert.equal(next.bank,1150);assert(!next.buyCareer('boots'));});
test('standing held attack faces an enemy behind, while movement retains intentional facing',()=>{const {g}=dock();g.player.x=10;g.player.face=1;const e=g.spawn('boarder',8.8,false);e.climb=0;tick(g,.3,{attack:true});assert.equal(g.player.face,-1);assert(e.hp<45);tick(g,.025,{move:1,attack:true});assert.equal(g.player.face,1);});
test('late but connected cargo interior entrance tolerates positions throughout the car',()=>{const {g}=dock();g.t=.262;g.player.x=12.45;assert(g.interact());assert.equal(g.playerLayer,'DEPOT');assert(g.pickupCargo(g.cargoCrates.find(c=>c.location==='depot'&&c.x===1)));assert(g.interact());assert.equal(g.storedCargo,1);assert.equal(g.playerLayer,'INTERIOR');});
test('early stopped train can request slow docking and aligns without teleporting',()=>{const {g}=dock();g.t=.247;const before=g.t;assert(g.interact());assert.equal(g.playerLayer,'INTERIOR');assert.equal(g.speedMode,'SLOW');assert.equal(g.t,before);tick(g,5.3);assert.equal(g.t,.26);assert.equal(g.speedMode,'STOP');assert(g.interact());assert.equal(g.playerLayer,'DEPOT');});
test('next lap expires old seals and offers one fresh shipment seal, never a reload seal',()=>{const {g}=dock();collect(g);const old=g.cargoCrates.find(c=>c.location==='stored');g.finish();g.completeArrival();g.more();g.chooseRoute('freight');g.chooseCar('cargo');g.start();assert.equal(old.protectedUntil,0);g.player.x=12.45;assert(g.pickupCargo(old));assert(g.loadCargo());assert.equal(old.protectedUntil,0);g.t=.26;g.speedMode='STOP';collect(g,-3);assert.equal(g.cargoCrates.filter(c=>c.protectedUntil>0).length,1);});
test('malformed career values cannot produce oversized or nonfinite benefits',()=>{assert.deepEqual(cleanSave({career:{boots:Infinity,hull:-10,kit:NaN}}).career,{boots:0,hull:0,kit:0});assert.deepEqual(cleanSave({career:{boots:99,hull:99,kit:99}}).career,{boots:3,hull:3,kit:1});});
test('twenty-second UI reading under two active saboteurs retains a recoverable train; guard cannot refresh',()=>{const {g}=dock();g.speedMode='CRUISE';const a=g.spawn('saboteur',5.8,false),b=g.spawn('saboteur',5.8,false);a.climb=b.climb=0;g.speedMode='STOP';assert(g.interact());assert(g.interact());const until=g.depotGuardUntil;tick(g,20);assert(g.cars[0].hp>=100,`engine after20s: ${g.cars[0].hp}`);assert.equal(g.status,'running');assert(g.interact());assert.equal(g.storedCargo,1);assert(g.interact());assert.equal(g.depotGuardUntil,until);tick(g,16);const before=g.cars[0].hp;g.damageCar(0,20,'saboteur',true);assert.equal(g.cars[0].hp,before-20);});
test('recovery feedback follows remaining live theft, expires and never pays a second cargo credit',()=>{const {g}=dock();collect(g);collect(g,-3);tick(g,19);g.speedMode='CRUISE';const thieves=[g.spawn('thief',12.45,false),g.spawn('thief',12.45,false)];thieves.forEach(e=>e.climb=0);g.speedMode='STOP';tick(g,3);assert.equal(g.cargoLedger.atRisk,900);assert.match(cargoNotice(g),/900/);const pending=g.money;g.hitEnemy(thieves[0],99);assert.equal(g.cargoLedger.atRisk,450);assert.match(cargoNotice(g),/被抱走 450/);assert.match(g.event,/仍有货物被抱走 450/);g.hitEnemy(thieves[1],99);assert.equal(g.cargoLedger.atRisk,0);assert.match(cargoNotice(g),/已追回/);assert.doesNotMatch(g.event,/仍有|逃离前|追击/);assert.equal(g.money,pending);assert.equal(g.bank,0);tick(g,85);assert.doesNotMatch(cargoNotice(g),/被抱走|追击|已追回/);assert.equal(g.money,1900);assert.doesNotMatch(g.event,/被抱走|追击|逃离前/);});
test('loss feedback replaces chase, expires, and clears on settlement, continuation and failure',()=>{const {g}=dock();collect(g);tick(g,19);const e=g.spawn('thief',12.45,false);e.climb=0;tick(g,11);assert.equal(g.cargoLedger.atRisk,0);assert.equal(g.money,1000);assert.match(cargoNotice(g),/丢失/);tick(g,6);assert.doesNotMatch(cargoNotice(g),/被抱走|追击|丢失/);g.finish();g.completeArrival();g.cashout();assert.equal(g.cargoChange,null);assert.equal(cargoNotice(g),'');const next=dock().g;collect(next);next.finish();next.completeArrival();next.more();assert.equal(next.cargoChange,null);const failed=dock().g;collect(failed);failed.fail();assert.equal(failed.cargoChange,null);assert.equal(cargoNotice(failed),'');assert.equal(new Game().cargoChange,null);});
