import test from 'node:test';import assert from 'node:assert/strict';
import {Game,B} from '../src/sim.js';import {ROUTES} from '../src/content.js';import {V11} from '../src/balance.js';
const tick=(g,t,input={})=>{for(let left=t;left>1e-8;left-=.025)g.step(Math.min(.025,left),input);};
function ready(bank=20000,prep={}){return new Game({bank,prep,seed:12345});}
function running(prep={}){const g=ready(0,prep);g.chooseRoute('industrial');g.chooseCar('cargo');g.start();g.elapsed=3;g.player.x=V11.consoleX;return g;}
test('Prep Shop spends Bank only at Roundhouse and obeys exact inventory caps',()=>{const g=ready();assert(g.buyPrep('reroll'));assert(g.buyPrep('repairKit'));assert(g.buyPrep('intel'));assert.equal(g.bank,8000);assert.deepEqual(g.prep,{reroll:1,repairKit:1,intel:1});g.prep.reroll=3;assert(!g.buyPrep('reroll'));assert.equal(g.bank,8000);g.chooseRoute('freight');assert(!g.buyPrep('intel'));});
test('cashout opens Bank spending while pre-cashout complete state cannot spend it',()=>{const g=running();g.finish();tick(g,B.arrivalTime);g.bank=5000;assert.equal(g.status,'complete');assert(!g.buyPrep('reroll'));assert(g.cashout());const before=g.bank;assert(g.buyPrep('reroll'));assert.equal(g.bank,before-3000);});
test('car reroll changes a real offered alternative once and consumes exactly one token',()=>{const g=ready(0,{reroll:1});assert(g.chooseRoute('industrial'));assert.deepEqual(g.carOffers,['workshop','cargo']);assert(!g.chooseCar('battery'));assert(g.rerollCars());assert.deepEqual(g.carOffers,['workshop','battery']);assert.equal(g.prep.reroll,0);assert(g.carRerolled);assert(!g.rerollCars());assert(!g.chooseCar('cargo'));assert(g.chooseCar('battery'));});
test('existing no-token route flow preserves cargo as an optional choice on all three routes',()=>{for(const route of Object.keys(ROUTES)){const g=ready();assert(g.chooseRoute(route));assert(g.carOffers.includes('cargo'),route);assert(g.chooseCar('cargo'),route);}});
test('Route Intel is consumed at the next route-choice screen and reveals one authored real event',()=>{const g=ready(4000,{intel:1});const intel=g.prepareRouteIntel();assert(intel);assert.equal(g.prep.intel,0);assert.equal(intel.text,ROUTES[intel.route].intel);assert.equal(g.prepareRouteIntel(),intel);g.chooseRoute('freight');assert.equal(g.routeIntel,intel);});
test('buying Intel while already at route choice makes it eligible immediately',()=>{const g=ready(4000);g.prepareRouteIntel();assert.equal(g.routeIntel,null);assert(g.buyPrep('intel'));const intel=g.prepareRouteIntel();assert(intel);assert.equal(g.prep.intel,0);assert.equal(g.bank,0);});
test('Emergency Repair Kit equips once per run, halves emergency channel and is consumed only on success',()=>{const g=running({repairKit:1});assert.equal(g.prep.repairKit,0);assert.equal(g.runRepairKit,1);g.damageCar(0,g.cars[0].hp);assert.equal(g.engineState,'stalled');assert.equal(g.emergencyRepairTime,B.restartTime/V11.kitSpeed);tick(g,1.475,{repair:true});assert.equal(g.engineState,'stalled');assert.equal(g.runRepairKit,1);tick(g,.025,{repair:true});assert.equal(g.engineState,'critical');assert.equal(g.runRepairKit,0);});
test('interrupted emergency channel does not waste the kit',()=>{const g=running({repairKit:1});g.damageCar(0,g.cars[0].hp);tick(g,.5,{repair:true});g.cancelRepair('released');assert.equal(g.runRepairKit,1);assert.equal(g.engineState,'stalled');tick(g,1.5,{repair:true});assert.equal(g.runRepairKit,0);assert.notEqual(g.engineState,'stalled');});
test('One More Round does not equip a second kit and preserves unused run kit',()=>{const g=running({repairKit:1});assert.equal(g.runRepairKit,1);g.finish();tick(g,B.arrivalTime);assert(g.more());assert(g.chooseRoute('freight'));assert(g.chooseCar('cargo'));assert(g.start());assert.equal(g.runRepairKit,1);assert.equal(g.prep.repairKit,0);});
test('ordinary death does not consume Prep inventory or the carried run repair kit',()=>{const g=running({repairKit:1,reroll:2});g.killPlayer();tick(g,5);assert.equal(g.runRepairKit,1);assert.equal(g.prep.reroll,2);assert.equal(g.player.hp,60);});
