import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,car,FLOOR,ROOF,LENGTH,B,stationX} from '../src/sim.js';
function advance(g,t,input={}){for(let i=0;i<Math.round(t/.025);i++)g.step(.025,input);}
function fresh(options={}){const g=new Game(options);g.start();return g;}
function dock(g){g.finish();advance(g,B.arrivalTime);}
function stall(g,x=5.8){g.player.x=x;g.damageCar(0,g.cars[0].hp,'test');}
const near=(a,b)=>assert(Math.abs(a-b)<1e-5,`${a} != ${b}`);

test('departure starts at zero and cannot double-start',()=>{const g=new Game();advance(g,5);assert.equal(g.t,0);g.start();assert.equal(g.phase,'depart');assert.equal(g.start(),false);});
test('pause freezes route, enemies, rescue, repair and recovery',()=>{const g=fresh();stall(g);advance(g,.5,{repair:true});g.director.rest=4;g.pause(true);const s=g.snapshot();advance(g,3,{move:1,attack:true,repair:true});assert.deepEqual(g.snapshot(),s);});
test('normal repair is a channel, not a click or per-frame heal',()=>{const g=fresh();g.player.x=stationX(0);g.cars[0].hp=80;advance(g,1,{repair:true});assert.equal(g.cars[0].hp,80);advance(g,.8,{repair:true});assert.equal(g.cars[0].hp,108);assert.equal(g.snapshot().engineHp,108);advance(g,.15,{repair:true});assert.equal(g.cars[0].hp,108);});
test('repair requires station proximity and stays on the ground',()=>{const g=fresh();g.cars[0].hp=80;g.player.x=.4;advance(g,2,{repair:true});assert.equal(g.cars[0].hp,80);g.player.x=5.8;g.player.roof=true;advance(g,2,{repair:true});assert.equal(g.cars[0].hp,80);});
test('moving, releasing and damage interrupt without partial HP gain',()=>{for(const action of ['move','released','damage']){const g=fresh();g.player.x=5.8;g.cars[0].hp=80;advance(g,.7,{repair:true});if(action==='damage')g.hurt(1,'test');else advance(g,.025,action==='move'?{move:1,repair:true}:{});assert.equal(g.cars[0].hp,80);assert.equal(g.repairJob,null);}});
test('engine transitions damaged -> critical -> stalled and never dies instantly',()=>{const g=fresh();g.damageCar(0,100);assert.equal(g.engineState,'damaged');g.damageCar(0,40);assert.equal(g.engineState,'critical');g.damageCar(0,40);assert.equal(g.engineState,'stalled');assert.equal(g.status,'running');assert(g.rescue.remaining>=8);});
test('front-engine rescue window is eight seconds and pauses route',()=>{const g=fresh();stall(g);const t=g.t;advance(g,7.975);assert.equal(g.status,'running');assert.equal(g.t,t);advance(g,.025);assert.equal(g.status,'lost');assert.equal(g.failReason,'engine_timeout');});
test('emergency restart succeeds and is counted once, no cash bonus',()=>{const g=fresh();stall(g);advance(g,3,{repair:true});near(g.cars[0].hp,36);assert.equal(g.rescue,null);assert.equal(g.total.clutchSaves,1);assert.equal(g.money,1000);assert.equal(g.engineShield,4);assert.equal(g.director.rest,8);advance(g,.2,{repair:true});assert.equal(g.total.clutchSaves,1);});
test('rescue can complete exactly at deadline, never after deadline',()=>{const a=fresh();stall(a);a.rescue.remaining=3;advance(a,3,{repair:true});assert.equal(a.status,'running');assert.equal(a.total.clutchSaves,1);const b=fresh();stall(b);b.rescue.remaining=2.99;advance(b,3,{repair:true});assert.equal(b.status,'lost');assert.equal(b.total.clutchSaves,0);});
test('12-car grace includes return travel and three-second repair',()=>{const g=fresh();while(g.cars.length<12)g.cars.push(car('cargo'));stall(g,g.length-.4);const travel=(g.player.x-stationX(0)-B.repairRadius)/B.walk;assert(g.rescue.window>=travel+B.restartTime+B.rescueMargin);advance(g,travel+.025,{move:-1});advance(g,3,{repair:true});assert.equal(g.status,'running');assert.equal(g.total.clutchSaves,1);});
test('carried cargo detour is included in emergency grace',()=>{const g=fresh();g.cars.push(car('workshop'));g.player.carry=true;stall(g,g.length-.4);const drop=2*LENGTH-.4;const expected=(g.player.x-drop)/B.carrySpeed+(drop-stationX(0)-B.repairRadius)/B.walk+1;assert(g.rescue.window>=expected+B.restartTime+B.rescueMargin);});
test('engine restart shield prevents instant relapse, expires normally',()=>{const g=fresh();stall(g);advance(g,3,{repair:true});g.damageCar(0,180);assert.equal(g.cars[0].hp,36);advance(g,4.05);g.damageCar(0,180);assert.equal(g.engineState,'stalled');assert(g.rescue);});
test('critical repair milestone has no repeatable payout',()=>{const g=fresh();g.player.x=5.8;g.cars[0].hp=10;advance(g,1.8,{repair:true});assert.equal(g.total.clutchRepairs,1);g.cars[0].hp=10;advance(g,2.2,{repair:true});assert.equal(g.total.clutchRepairs,1);assert.equal(g.money,1000);});
test('ladder proximity is required and carrying blocks layer changes',()=>{const g=fresh();g.player.x=.5;assert(!g.layer());g.player.x=4.2;assert(g.layer());g.player.carry=true;assert(!g.layer());});
test('roof is 25 percent faster, carrying remains slow',()=>{const a=fresh(),b=fresh();b.player.roof=true;b.player.y=ROOF;advance(a,1,{move:1});advance(b,1,{move:1});near((b.player.x-3)/(a.player.x-3),1.25);});
test('melee does not cross layers',()=>{const g=fresh();const e=g.spawn('boarder',4,true);e.climb=0;g.attack();advance(g,.24);assert.equal(e.hp,2);});
test('melee windup, cooldown and knockback preserved',()=>{const g=fresh();const e=g.spawn('boarder',4,false);e.climb=0;g.attack();assert(!g.attack());assert.equal(e.hp,2);advance(g,.19);assert.equal(e.hp,1);assert(e.x>4);});
test('floor enemies cannot hit roof player',()=>{const g=fresh();g.player.y=ROOF;g.player.roof=true;const e=g.spawn('boarder',3,false);e.climb=0;advance(g,2);assert.equal(g.player.hp,100);});
test('crane collision still matches actual sweep coordinates',()=>{const g=fresh();g.t=.37;g.phase='crane';g.player.roof=true;g.player.y=ROOF;g.player.x=.5;advance(g,.05);assert.equal(g.player.hp,100);g.player.x=g.craneX;advance(g,.025);assert.equal(g.player.hp,68);});
test('tunnel hits only roof, moves player to interior and blocks ascent',()=>{const g=fresh();g.t=.561;g.phase='tunnel';g.player.roof=true;g.player.y=ROOF;advance(g,.025);assert.equal(g.player.roof,false);assert.equal(g.player.hp,70);assert(!g.layer());advance(g,.15);assert.equal(g.player.hp,70);});
test('boost never removes four-second crane or six-second tunnel warning',()=>{const events=[];const g=fresh({emit:(t,d)=>events.push({t,...d})});g.player.x=5.8;g.t=.299;g.phase='yard';g.throttle=100;while(g.t<.341&&g.status==='running')g.step(.025);assert(g.warningAge('crane')>=4);g.t=.459;g.phase='crane';while(g.t<.561&&g.status==='running')g.step(.025);assert(g.warningAge('tunnel')>=6);assert(events.some(x=>x.t==='hazard_warning'));});
test('projectile uses authored socket and expires at range',()=>{const g=fresh();g.round=3;g.attack();assert.equal(g.projectiles[0].x,g.muzzle().x);assert.equal(g.projectiles[0].y,g.muzzle().y);advance(g,.5);assert.equal(g.projectiles.length,0);});
test('projectile knockback keeps bullet direction after shooter turns',()=>{const g=fresh();g.round=3;const e=g.spawn('boarder',6,false);e.climb=0;g.attack();g.player.face=-1;advance(g,.08);assert(e.x>6);});
test('thief pickup does not debit; escape debits exactly one crate',()=>{const g=fresh();g.player.roof=true;const e=g.spawn('thief',12.4,false);e.climb=0;advance(g,1);assert(e.carry);assert.equal(g.cars[1].cargo,2);assert.equal(g.money,1000);advance(g,3);assert.equal(g.money,750);assert.equal(g.total.cargoLost,250);advance(g,1);assert.equal(g.total.cargoLost,250);});
test('recovering a crate is counted once and restores cargo, not duplicate money',()=>{const g=fresh();const e=g.spawn('thief',12.4,false);e.climb=0;advance(g,1);g.hitEnemy(e,99);g.hitEnemy(e,99);assert.equal(g.cars[1].cargo,3);assert.equal(g.total.cargoSaved,250);assert.equal(g.money,1050);});
test('cargo in a living thief hand is secured at arrival',()=>{const g=fresh();const e=g.spawn('thief',12.4,false);e.climb=0;advance(g,1);g.finish();assert.equal(g.cars[1].cargo,3);assert.equal(g.total.cargoSaved,0);});
test('boost is finite; battery adds usable charge',()=>{const g=fresh();g.interact();advance(g,1);assert(g.t>.015);advance(g,4);assert.equal(g.throttle,0);g.interact();advance(g,4.1);g.interact();assert.equal(g.throttle,0);g.cars.push(car('battery'));g.interact();assert.equal(g.cars[2].charge,65);assert.equal(g.throttle,4);});
test('powered workshop synergy speeds repair and disappears if battery breaks',()=>{const times=[];for(const hp of [100,0]){const g=fresh();g.cars.push(car('workshop'),car('battery'));g.cars[3].hp=hp;g.player.x=5.8;g.cars[0].hp=80;advance(g,.025,{repair:true});times.push(g.repairJob.duration);}near(times[1]/times[0],1.2);});
test('battery health transitions before total failure',()=>{const g=fresh();g.cars.push(car('battery'));g.syncSystems();assert.equal(g.batteryBand,'normal');g.cars[2].hp=40;g.syncSystems();assert.equal(g.batteryBand,'flicker');g.cars[2].hp=20;g.syncSystems();assert.equal(g.batteryBand,'emergency');g.cars[2].hp=0;g.syncSystems();assert.equal(g.batteryBand,'offline');});
test('low HP emits one band entry, without repeated per-frame alerts',()=>{const events=[];const g=fresh({emit:t=>events.push(t)});g.hurt(85,'test');advance(g,1);assert.equal(events.filter(t=>t==='player_near_death').length,1);near(g.total.criticalSeconds,1);});
test('budget admission never admits too many live enemies',()=>{for(let round=1;round<=9;round++){const g=fresh();g.round=round;for(let i=0;i<20;i++)g.spawn('boarder');assert(g.director.load(g)<=g.director.snapshot(g).cap);assert(g.enemies.length>0);}});
test('recovery blocks new spawns but never deletes existing threats',()=>{const g=fresh();const e=g.spawn('boarder',16,false);g.t=.21;g.phase='yard';g.director.recover(g,'test');advance(g,5);assert.equal(g.enemies.length,1);assert.equal(g.enemies[0].id,e.id);near(g.director.rest,3);});
test('fault is warned, finite and solved by repair',()=>{const events=[];const g=fresh({emit:t=>events.push(t)});g.round=3;g.t=.121;g.phase='yard';g.player.x=5.8;advance(g,.025);assert(g.director.fault);const hp=g.cars[0].hp;advance(g,2.9);assert.equal(g.cars[0].hp,hp);advance(g,1.2);assert(g.cars[0].hp<hp);advance(g,1.8,{repair:true});assert.equal(g.director.fault,null);assert(g.director.rest>0);assert(events.includes('engine_fault_warning'));});
test('no scripted fault in first two rounds or while player is weak',()=>{for(const [round,hp] of [[1,100],[2,100],[4,35]]){const g=fresh();g.round=round;g.player.hp=hp;g.t=.121;g.phase='yard';advance(g,1);assert.equal(g.director.fault,null);}});
test('difficulty does not punish larger bank or current wallet',()=>{const a=fresh(),b=fresh({bank:9999999});a.t=b.t=.22;a.phase=b.phase='yard';b.money=9999999;advance(a,10);advance(b,10);assert.deepEqual(a.enemies,b.enemies);assert.deepEqual(a.director.snapshot(a),b.director.snapshot(b));});
test('arrival releases for four seconds; pause and settlement guards work',()=>{const g=fresh();assert(!g.cashout());assert(g.finish());assert.equal(g.status,'arriving');assert(!g.cashout());advance(g,2);assert.equal(g.status,'arriving');g.pause(true);advance(g,5);assert.equal(g.status,'arriving');g.pause(false);advance(g,2);assert.equal(g.status,'complete');const cash=g.money;assert(g.cashout());assert(!g.cashout());assert.equal(g.bank,cash);assert.equal(g.money,0);});
test('stalled train cannot sneak into arrival or cashout',()=>{const g=fresh();g.t=.99999;stall(g);g.step(.05);assert.equal(g.status,'running');assert(!g.finish());assert(!g.cashout());advance(g,8);assert.equal(g.status,'lost');assert.equal(g.bank,0);});
test('fatal player damage still wins over arrival',()=>{const g=fresh();g.t=.99999;g.hurt(200,'boarder');g.step(.05);assert.equal(g.status,'lost');assert.equal(g.bank,0);});
test('continuing preserves hull, resets lap not run stats, restarts departure',()=>{const g=fresh();g.cars[0].hp=120;g.inc('cargoSaved',250);dock(g);assert(g.more('battery'));assert.equal(g.cars.length,3);assert.equal(g.cars[0].hp,120);assert.equal(g.lap.cargoSaved,0);assert.equal(g.total.cargoSaved,250);g.start();assert.equal(g.phase,'depart');assert.equal(g.t,0);});
test('bank preserved in failure and restart constructors',()=>{const g=fresh({bank:4123});g.fail();assert.equal(g.bank,4123);const next=new Game({bank:g.bank});assert.equal(next.bank,4123);});
test('broken workshop cannot charge for healing',()=>{const g=fresh();g.cars.push(car('workshop'));g.player.x=20;g.player.hp=50;g.cars[2].hp=0;g.interact();assert.equal(g.player.hp,50);assert.equal(g.money,1000);});
test('practice is explicit and cannot bank or continue into a real run',()=>{const g=fresh({bank:4000,practice:true});stall(g);advance(g,3,{repair:true});assert.equal(g.status,'practice_complete');assert.equal(g.bank,4000);assert(!g.cashout());assert(!g.more('cargo'));assert.equal(g.snapshot().mode,'practice');});
test('damaged/critical speed reduction is bounded',()=>{const g=fresh();g.cars[0].hp=80;g.syncSystems();near(g.speed,.92);g.cars[0].hp=20;g.syncSystems();near(g.speed,.8);});
test('risk descriptor uses actual train state, not a claimed success probability',()=>{const g=fresh();assert.equal(g.risk(),'LOW');g.cars[0].hp=10;g.player.hp=20;assert(['HIGH','EXTREME'].includes(g.risk()));});
