import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import * as T from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const source=fs.readFileSync(new URL('../src/train_cutaway.js',import.meta.url),'utf8').replace('../vendor/three.module.min.js',new URL('../node_modules/three/build/three.module.js',import.meta.url).href);
const {fitCarUpperBody}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
globalThis.ProgressEvent??=class {constructor(type,data){this.type=type;Object.assign(this,data);}};
async function load(file){const bytes=fs.readFileSync('assets/kenney/train/'+file+'.glb'),json=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12))),base=28+bytes.readUInt32LE(12);json.buffers[0].uri='data:application/octet-stream;base64,'+bytes.subarray(base,base+json.buffers[0].byteLength).toString('base64');json.images=[];json.textures=[];json.materials=[];for(const m of json.meshes)for(const p of m.primitives)delete p.material;return (await new GLTFLoader().parseAsync(JSON.stringify(json),'')).scene;}
function fit(model,size){model.rotation.y=-Math.PI/2;model.updateMatrixWorld(true);const box=new T.Box3().setFromObject(model),extent=box.getSize(new T.Vector3()),centre=box.getCenter(new T.Vector3()),group=new T.Group();group.add(model);group.scale.set(size[0]/extent.x,size[1]/extent.y,size[2]/extent.z);model.position.set(-centre.x,-box.min.y,-centre.z);return group;}
for(const [file,size,position,name] of [['train-diesel-a',[7.4,2.65,1.65],[0,.14,-.72],'train-diesel-a'],['train-carriage-container-red',[7.5,3.35,1.15],[0,0,-1.05],'cargo']])test('actual GLTFLoader '+file+' integrates its upper body while retaining bogies and lower vertices',async()=>{
 const original=await load(file),model=fit(original,size);model.position.fromArray(position);const car=new T.Group();car.add(model);car.updateMatrixWorld(true);let body;const wheels=[];original.traverse(o=>{if(o.isMesh&&(o.name===name||o.name===name+'_1'))body=o;if(o.isMesh&&o.name.startsWith('wheels-'))wheels.push({o,geometry:o.geometry,p:o.position.toArray(),q:o.quaternion.toArray()});});assert(body,'production loader node must be found');
 const geometry=body.geometry,before=Array.from(geometry.getAttribute('position').array),uv=Array.from(geometry.getAttribute('uv').array),matrix=body.matrixWorld.clone();assert.equal(fitCarUpperBody(model,car,{names:[name]}),1);assert.notEqual(body.geometry,geometry);assert.deepEqual(Array.from(geometry.getAttribute('position').array),before);assert.deepEqual(Array.from(body.geometry.getAttribute('uv').array),uv);
 let highest=-Infinity,lower=0;for(let i=0;i<geometry.getAttribute('position').count;i++){
  const a=new T.Vector3().fromBufferAttribute(geometry.getAttribute('position'),i).applyMatrix4(matrix),b=new T.Vector3().fromBufferAttribute(body.geometry.getAttribute('position'),i).applyMatrix4(matrix);assert(Math.abs(a.x-b.x)<1e-5&&Math.abs(a.z-b.z)<1e-5);if(a.y<=1.12){assert(Math.abs(a.y-b.y)<1e-5);lower++;}highest=Math.max(highest,b.y);
 }assert(Math.abs(highest-4.04)<1e-5);if(name==='train-diesel-a')assert(lower>0,'chassis below floor stays authored');
 assert(wheels.length===2);for(const w of wheels){assert.equal(w.o.geometry,w.geometry);assert.deepEqual(w.o.position.toArray(),w.p);assert.deepEqual(w.o.quaternion.toArray(),w.q);}
});
