import test from 'node:test';import assert from 'node:assert/strict';
import {Game,car,DEFS,B,stationX} from '../src/sim.js';import {CARS} from '../src/content.js';import {V11} from '../src/balance.js';
const tick=(g,t,input={})=>{for(let left=t;left>1e-8;left-=.025)g.step(Math.min(.025,left),input);};
const close=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function game(types=[]){const g=new Game();g.chooseRoute('industrial');g.chooseCar('cargo');g.start();g.elapsed=3;g.t=.1;g.phase='yard';g.cars.push(...types.map(car));g.player.x=5.8;return g;}
test('Car identities and HP come from the content/balance sources',()=>{for(const id of Object.keys(CARS)){assert.equal(car(id).max,V11.carHP[id]);assert.equal(DEFS[id].name,CARS[id].label);}});
test('Battery extends actual FAST endurance, and empty charge automatically drops to CRUISE',()=>{const base=game(),built=game(['battery']);for(const g of [base,built]){assert(g.setSpeed('FAST'));tick(g,8.4);}assert.equal(base.speedMode,'CRUISE');assert.equal(built.speedMode,'FAST');assert(built.batteryCharge>90);assert(built.t>base.t);});
test('Battery alone gives a genuine twenty-percent repair speed bonus above twenty-five percent charge',()=>{const g=game(['battery']);g.damageCar(0,40);g.repair(.025);close(g.repairJob.duration,1.5);close(g.repairSpeed,1.2);g.cars[2].charge=25;g.repair(.025);close(g.repairJob.duration,1.8);close(g.repairSpeed,1);g.cars[2].charge=26;g.repair(.025);close(g.repairJob.duration,1.5);});
test('Workshop and powered repair stack; lost power changes a running repair channel',()=>{const g=game(['workshop','battery']);g.damageCar(0,40);g.repair(.025);close(g.repairJob.duration,1.2);close(g.repairSpeed,1.5);g.damageCar(3,100);g.repair(.025);close(g.repairJob.duration,1.44);g.damageCar(2,120);g.repair(.025);close(g.repairJob.duration,1.8);});
test('Workshop accelerates a real normal Engine repair with the same HP reward',()=>{const g=game(['workshop']);g.damageCar(0,40);tick(g,1.425,{repair:true});assert.equal(g.cars[0].hp,140);tick(g,.025,{repair:true});assert.equal(g.cars[0].hp,168);assert.equal(g.lap.repairs,1);});
test('Workshop accelerates emergency restart without extending the rescue deadline',()=>{const g=game(['workshop']);g.damageCar(0,180);const entered=g.rescue.entered;tick(g,2.375,{repair:true});assert.equal(g.engineState,'stalled');assert.equal(g.rescue.entered,entered);tick(g,.025,{repair:true});assert.equal(g.cars[0].hp,36);assert.equal(g.lap.clutchSaves,1);assert.equal(g.rescue,null);});
test('an intact Workshop can clear an active industrial fault locally through a real repair channel',()=>{const g=game(['workshop']);g.round=3;g.t=.151;g.step(.025);assert(g.director.fault);g.player.x=stationX(2);tick(g,.95,{repair:true});assert(g.director.fault);tick(g,.025,{repair:true});assert.equal(g.director.fault,null);assert.equal(g.cars[2].hp,120);assert.equal(g.lap.repairs,1);assert.match(g.repairHint,/FAULT CLEARED/);});
test('Cargo and Battery cars cannot service a remote Engine fault when already intact',()=>{const g=game(['battery']);g.round=3;g.t=.151;g.step(.025);for(const i of [1,2]){g.player.x=stationX(i);assert(!g.repair(.025));assert.equal(g.repairJob,null);assert(g.director.fault);}});
test('charge and damage affect lighting supply; a dead Battery grants neither charge nor repair bonuses',()=>{const g=game(['battery']);close(g.power,1);g.cars[2].charge=10;g.syncSystems();close(g.power,.1);assert.equal(g.batteryBand,'emergency');g.damageCar(2,100);close(g.power,0);close(g.repairSpeed,1);assert.equal(g.batteryCapacity,100);assert.equal(g.batteryBand,'offline');});
test('Dock refills base and car charge before settlement, even without One More Round',()=>{const g=game(['battery']);g.boostCharge=0;g.cars[2].charge=0;g.finish();tick(g,4);assert.equal(g.status,'complete');assert.equal(g.batteryCharge,200);assert.equal(g.batterySupply,1);});
test('Workshop healing cannot spend pledged Cargo Value',()=>{const g=game(['workshop']);g.createCargo(450,'stored',{carIndex:1,secured:true});g.money=450;g.player.hp=60;g.player.x=stationX(2);assert(!g.interact());assert.equal(g.money,450);assert.equal(g.cargoValue,450);g.money=570;assert(g.interact());assert.equal(g.money,450);assert.equal(g.cargoValue,450);assert.equal(g.player.hp,80);});
