import test from'node:test';import assert from'node:assert/strict';import {Game,DURATION}from'../src/sim.js';import {BUILD}from'../src/balance.js';import fs from'node:fs';
const tick=(g,n,input={})=>{for(let i=0;i<Math.round(n/.025);i++)g.step(.025,input);};const start=()=>{const g=new Game({seed:357595083});g.chooseRoute('freight');g.chooseCar('cargo');g.start();g.elapsed=40;g.t=.28;g.player.x=12.45;return g;};
test('reverse requires a brake dwell, moves backwards and automatically stops at missed depot without teleport',()=>{const g=start();assert(!g.changeDirection());g.emergencyStop();assert(!g.changeDirection());tick(g,.5);assert(g.changeDirection());assert.equal(g.speedMode,'REVERSE');const before=g.t;assert(g.interact());assert.equal(g.dockingDepot,g.depots[0].id);tick(g,1);assert(g.t<before);assert(g.t>.26);tick(g,10);assert.equal(g.t,.26);assert.equal(g.speedMode,'STOP');assert(g.interact());assert.equal(g.playerLayer,'DEPOT');assert(g.interact());assert.equal(g.heldCargo.value,450);});
test('reverse and returning across a station never replenish cargo, credit it twice or renew guards',()=>{const g=start();g.t=.26;g.speedMode='STOP';g.interact();g.interact();g.interact();assert.equal(g.money,1450);const seal=g.cargoCrates.find(c=>c.location==='stored').protectedUntil,guard=g.depotGuardUntil,stock=g.cargoCrates.filter(c=>c.location==='depot').length;g.emergencyStop();tick(g,.5);g.changeDirection();tick(g,2);g.emergencyStop();tick(g,.5);g.changeDirection();g.interact();tick(g,2.1);g.interact();assert.equal(g.depotGuardUntil,guard);assert.equal(g.money,1450);assert.equal(g.cargoCrates.filter(c=>c.location==='depot').length,stock);assert.equal(g.cargoCrates.find(c=>c.location==='stored').protectedUntil,seal);});
test('stop reading budget is cumulative, direction changes cannot reset admission age, late pressure returns',()=>{const g=start();g.emergencyStop();tick(g,19);assert.equal(g.director.spawns,0);const key=g.director.stopKey(g);g.speedMode='SLOW';tick(g,1);g.speedMode='STOP';tick(g,1);assert(g.director.stopAges.get(key)>=20-1e-8);tick(g,16);assert.equal(g.director.snapshot(g).stopStage,'pressure');assert(g.director.spawns>0);});
test('reverse at route zero stops at the boundary and cannot complete a lap or replay progress rewards',()=>{const g=start();g.t=.0001;g.emergencyStop();tick(g,.5);g.changeDirection();tick(g,1);assert.equal(g.t,0);assert.equal(g.speedMode,'STOP');assert.equal(g.status,'running');assert.equal(g.round,1);assert.equal(g.money,1000);});
test('V12 metadata and local licensed GLB texture dependencies are coherent',()=>{assert.match(BUILD,/^V12-/);assert.equal(JSON.parse(fs.readFileSync('package.json')).version,'12.0.0');const manifest=JSON.parse(fs.readFileSync('assets/kenney/manifest.json'));let count=0;for(const [pack,p]of Object.entries(manifest.packs)){assert.match(fs.readFileSync('assets/kenney/'+p.licenseFile,'utf8'),/Creative Commons Zero/);for(const m of p.models){const b=fs.readFileSync('assets/kenney/'+pack+'/'+m.file);assert.equal(b.length,m.bytes);const j=JSON.parse(b.toString('utf8',20,20+b.readUInt32LE(12)));for(const image of j.images||[])assert(fs.existsSync('assets/kenney/'+pack+'/'+image.uri));count++;}}assert(count>=15);});
test('stationary overhead hazard passes front to rear, pauses with STOP, and reverses without mismatching collision',()=>{const g=start();g.t=.50;g.phase='crane';g.speedMode='CRUISE';const x=g.craneX;tick(g,1);assert(g.craneX>x);g.emergencyStop();const stopped=g.craneX;tick(g,.5);assert.equal(g.craneX,stopped);g.changeDirection();tick(g,1);assert(g.craneX<stopped);const warning=g.hazardInfo();assert(g.phase==='crane');g.player.x=g.craneX;g.player.roof=true;g.player.y=4.12;const hp=g.player.hp;tick(g,.025);assert(g.player.hp<hp);});

test('first docking ward survives old boarders for 20s, ends at 25s, and cannot refresh through station visits or braking',()=>{const g=start();g.t=.26;const e=g.spawn('boarder',12.45,false);e.climb=0;g.emergencyStop();const until=g.dockingPlayerUntil;const hp=g.player.hp;tick(g,20);assert.equal(g.player.hp,hp);assert.equal(g.player.deathCount,0);assert(g.dockingPlayerRemaining>4.9);g.interact();g.interact();g.interact();g.emergencyStop();assert.equal(g.dockingPlayerUntil,until);tick(g,6);g.hurt(12,'boarder');assert(g.player.hp<hp);tick(g,35);assert.equal(g.dockingPlayerRemaining,0);assert(g.director.spawns>0);});
test('docking ward blocks only enemy damage near that station and never protects against overhead hazards or later rounds',()=>{const g=start();g.t=.26;g.emergencyStop();assert.equal(g.dockingPlayerRemaining,25);const hp=g.player.hp;g.hurt(12,'boarder');assert.equal(g.player.hp,hp);g.hurt(12,'crane');assert.equal(g.player.hp,hp-12);g.player.invul=0;g.round=2;g.hurt(12,'boarder');assert.equal(g.player.hp,hp-24);g.round=1;g.t=.4;assert.equal(g.dockingPlayerRemaining,0);});

test('hazard approach ETA is finite only when advancing, not stopped, reversed, stalled or paused',()=>{const g=start();g.route='tunnel';g.t=.33;g.speedMode='CRUISE';let h=g.hazardInfo();assert.equal(h.motion,'approaching');assert(h.seconds>0);g.emergencyStop();h=g.hazardInfo();assert.equal(h.motion,'stopped');assert.equal(h.seconds,null);tick(g,.5);g.changeDirection();h=g.hazardInfo();assert.equal(h.motion,'away');assert.equal(h.seconds,null);g.emergencyStop();tick(g,.5);g.changeDirection();assert(g.hazardInfo().seconds>0);g.paused=true;assert.equal(g.hazardInfo().seconds,null);g.paused=false;g.damageCar(0,g.cars[0].hp,'test');assert.equal(g.hazardInfo().motion,'stopped');assert.equal(g.hazardInfo().seconds,null);});
test('hazard UI has direction-specific states and no numeric countdown during non-approach motion',async()=>{const {hazardETA}=await import('../src/playability_ui.js');assert.match(hazardETA({kind:'tunnel',motion:'approaching',seconds:8}),/8.0 秒/);for(const motion of ['stopped','away','paused']){const text=hazardETA({kind:'tunnel',motion,seconds:null});assert(!/约|NaN|Infinity/.test(text));assert.match(text,/无.*倒计时/);}assert.match(hazardETA({kind:'crane',motion:'away',seconds:null}),/扫顶.*远离/);});

test('roof warning identifies the actual route hazard: red-edged crane only, low-clearance tunnel separately',async()=>{const {roofHazardHint}=await import('../src/playability_ui.js');assert.match(roofHazardHint('crane'),/红边横栏/);for(const phase of ['approach','tunnel']){assert.match(roofHazardHint(phase),/隧道低净空/);assert(!roofHazardHint(phase).includes('红边'));}});
