import {chromium} from 'playwright';import fs from 'node:fs';
const port=process.env.QA_PORT||8779,minutes=Number(process.env.QA_MINUTES||12),label=process.env.QA_LABEL||'candidate',root=`artifacts/${label}`;fs.mkdirSync(root,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});const context=await browser.newContext({viewport:{width:1280,height:720},recordVideo:{dir:root,size:{width:960,height:540}}});const p=await context.newPage();let held=new Set(),seq=0;const events=[],errors=[],began=Date.now();p.on('pageerror',e=>errors.push(String(e)));const snap=()=>p.evaluate(()=>__RH_DEBUG.snapshot());
const record=async(action)=>{const s=await snap();events.push({wall:(Date.now()-began)/1000,action,...s});};
async function input(keys=[]){for(const k of held)if(!keys.includes(k))await p.keyboard.up(k);for(const k of keys)if(!held.has(k))await p.keyboard.down(k);held=new Set(keys);}
async function tap(k){await p.keyboard.press(k);await p.waitForTimeout(80);await record(k);}
async function screenshot(name){await p.screenshot({path:`${root}/${String(++seq).padStart(2,'0')}-${name}.png`});}
async function moveTo(x,combat=true){for(let i=0;i<300;i++){const s=await snap();if(!s.running||s.playerLifeState==='DEAD_WAITING_RESPAWN')break;if(Math.abs(s.px-x)<.25){await input(combat?['KeyJ','KeyK']:[]);return;}await input([s.px<x?'KeyD':'KeyA',...(combat?['KeyJ','KeyK']:[])]);await p.waitForTimeout(70);}await input([]);}
async function faceFight(){const s=await snap();const e=s.enemyStates.filter(e=>e.hp>0&&e.roof===s.roof).sort((a,b)=>Math.abs(a.x-s.px)-Math.abs(b.x-s.px))[0];if(e&&Math.sign(e.x-s.px)!==s.facing){await input([e.x<s.px?'KeyA':'KeyD','KeyJ','KeyK']);await p.waitForTimeout(45);}await input(['KeyJ','KeyK']);}
async function startRun(route='freight'){await input([]);await p.locator(`[data-route=${route}]`).click();await p.locator('[data-car=cargo]').click();await p.locator('#start').click();await record(`normal START ${route}/CARGO`);}
try{await p.goto(`http://127.0.0.1:${port}/`);await p.waitForFunction(()=>__RH_DEBUG?.snapshot().modelsLoaded===3);await screenshot('entry');await startRun();let depotDone=new Set(),lastShot=0,run=1;
while(Date.now()-began<minutes*60000){let s=await snap();if(errors.length)throw Error(errors.join(';'));if(s.status==='lost'||s.status==='cashed'){await input([]);await screenshot(s.status);if(s.status==='cashed'){for(const id of ['boots','hull','kit']){const b=p.locator(`[data-career=${id}]`);if(await b.count()&&!await b.isDisabled()){await b.click();await record('career '+id);}}}await p.locator('#restart').click();run++;depotDone=new Set();await startRun(['freight','industrial','tunnel'][(run-1)%3]);continue;}
if(s.status==='complete'){await input([]);await screenshot('arrival');await p.locator('#cash').click();await record('CASH OUT');continue;}
if(s.status==='arriving'||s.playerLifeState==='DEAD_WAITING_RESPAWN'){await input([]);await p.waitForTimeout(250);continue;}
if(s.paused){await p.locator('#pause').click();continue;}
if(s.rescue){await input([]);if(s.playerLayer==='DEPOT')await tap('KeyW');if(s.roof)await tap('KeyW');await moveTo(5.8,false);await input(['KeyE']);await p.waitForTimeout(400);continue;}
const marker=s.route==='freight'?.26:s.route==='industrial'?.66:.20;
if(!depotDone.has(marker)&&s.routeProgress>=marker-.013){await moveTo(12.45);s=await snap();if(s.routeProgress<marker){await faceFight();await p.waitForTimeout(100);continue;}depotDone.add(marker);await input([]);await tap('KeyB');if(label.startsWith('baseline'))await tap('KeyW');await tap('KeyF');await screenshot('depot');s=await snap();if(s.playerLayer==='DEPOT'){await tap('KeyF');if(Number(process.env.QA_IDLE_READ_SECONDS)>0){await p.waitForTimeout(Number(process.env.QA_IDLE_READ_SECONDS)*1000);await record('intentional read UI '+process.env.QA_IDLE_READ_SECONDS+' seconds');await screenshot('reading-window');}await tap('KeyF');if(label.startsWith('baseline'))await tap('KeyF');await screenshot('first-loaded');await tap('KeyF');s=await snap();if(s.playerLayer==='DEPOT'){await input(['KeyA']);await p.waitForTimeout(850);await input([]);if(label.startsWith('baseline'))await tap('KeyF');await screenshot('second-carry');await input(['KeyD']);await p.waitForTimeout(1000);await input([]);await tap('KeyF');if(label.startsWith('baseline'))await tap('KeyF');await screenshot('second-loaded');}
// Intentionally spend time observing risk with normal inputs; then respond to the theft warning.
for(let t=0;t<110;t++){s=await snap();if(s.playerLifeState==='DEAD_WAITING_RESPAWN')break;const thief=s.enemyStates.find(e=>e.type==='thief'&&['steal','escape'].includes(e.state));if(thief){await record('observed theft warning; normal return/rescue');await screenshot('theft-warning');if(s.playerLayer==='DEPOT')await tap('KeyW');if((await snap()).roof)await tap('KeyW');await moveTo(thief.x);await faceFight();await p.waitForTimeout(1500);await screenshot('rescue-attempt');break;}await faceFight();await p.waitForTimeout(200);}}
await input([]);s=await snap();if(s.playerLayer==='DEPOT')await tap('KeyW');s=await snap();if(s.roof){await moveTo(12.6,false);await tap('KeyW');}await moveTo(5.8);await input([]);await tap('KeyF');const cruise=p.locator('[data-speed=CRUISE]');if(await cruise.isVisible())await cruise.click();await record('resume CRUISE');continue;}
if(s.scrap>=12&&s.rangedWeapon===null&&s.routeProgress<marker-.04){await moveTo(1.7);await input([]);await tap('KeyF');const weapon=p.locator('[data-weapon=handgun]');if(await weapon.count()&&await weapon.isVisible()&&!await weapon.isDisabled()){await weapon.click();await record('purchase HANDGUN');await p.locator('#closeArmory').click();}else if(label.startsWith('baseline')){const melee=p.locator('[data-armory=melee]');if(!await melee.isDisabled())await melee.click();await p.locator('#closeArmory').click();} }
await faceFight();if(s.engineHp<80&&s.playerLayer==='INTERIOR'){await moveTo(5.8);await input(['KeyE']);await p.waitForTimeout(2200);}
if(Date.now()-lastShot>60000){lastShot=Date.now();await record('minute checkpoint');await screenshot('checkpoint');fs.writeFileSync(`${root}/progress.json`,JSON.stringify({events,errors,wallSeconds:(Date.now()-began)/1000},null,2));}
await p.waitForTimeout(180);
}
await record('continuous normal-input session complete');await screenshot('end');
}catch(e){errors.push(String(e));await screenshot('failure');}finally{await input([]);fs.writeFileSync(`${root}/normal-play.json`,JSON.stringify({mode:'release URL; read-only snapshots; keyboard and DOM clicks only; no mutable test hooks',events,errors,wallSeconds:(Date.now()-began)/1000,logs:await p.evaluate(()=>__RH_DEBUG?.logs()||[])},null,2));console.log(JSON.stringify({label,wallSeconds:(Date.now()-began)/1000,events:events.length,errors,last:events.at(-1)?.status}));await context.close();await browser.close();}
