import {Game,BUILD,DEFS,LENGTH,FLOOR,ROOF,phaseAt,clamp} from './sim.js';
import {View} from './view.js';
import {Telemetry} from './telemetry.js';
const $=id=>document.getElementById(id);let game,view,telemetry,input={move:0,attack:false,repair:false},last=0,lastStatus='',selected='battery',frameError=false,bankWritable=true;
function readBank(){try{const n=Number(localStorage.getItem('roundhouse_bank')||0);return Number.isFinite(n)&&n>=0?n:0}catch{return 0}}
function snapshot(){return{...game?.snapshot(),...(view?.loaded===3?view.snapshot():{modelsLoaded:0}),session:telemetry?.session,standalone:!!navigator.standalone||matchMedia('(display-mode: standalone)').matches,errors:telemetry?.errors||0}}
telemetry=new Telemetry(snapshot);game=new Game({bank:readBank(),emit:(type,data)=>telemetry.log(type,data)});
function clearInput(){input={move:0,attack:false,repair:false};pressed.clear();document.querySelectorAll('.active').forEach(e=>e.classList.remove('active'))}
function fatal(error){clearInput();game.pause(true);frameError=true;$('modal').hidden=true;$('portrait').hidden=true;telemetry.log('runtime_error',{message:String(error?.message||error).slice(0,150)});$('fatal').hidden=false;$('fatal').textContent='3D 运行暂停：'+String(error?.message||error)+'\n日志已保留。请刷新重试；此版本不会退回二维假模型。'}
const pressed=new Map();
function refreshInputs(){let move=0,attack=false,repair=false;for(const key of pressed.values()){if(key==='L')move=-1;if(key==='R')move=1;if(key==='attack')attack=true;if(key==='fix')repair=true}input={move,attack,repair}}
for(const id of ['L','R','attack','fix']){const el=$(id);el.addEventListener('pointerdown',e=>{e.preventDefault();if(game.paused||game.status!=='running')return;el.setPointerCapture(e.pointerId);pressed.set(e.pointerId,id);el.classList.add('active');refreshInputs();telemetry.log('input_down',{key:id,x:game.player.x})});const release=e=>{e.preventDefault();pressed.delete(e.pointerId);if(![...pressed.values()].includes(id))el.classList.remove('active');refreshInputs();telemetry.log('input_up',{key:id,x:game.player.x})};el.addEventListener('pointerup',release);el.addEventListener('pointercancel',release);el.addEventListener('lostpointercapture',()=>{for(const [k,v] of pressed)if(v===id)pressed.delete(k);refreshInputs();el.classList.remove('active')})}
const keys={a:'L',ArrowLeft:'L',d:'R',ArrowRight:'R',j:'attack',' ':'attack',e:'fix'};addEventListener('keydown',e=>{if(e.target?.tagName==='INPUT')return;const k=keys[e.key];if(k){e.preventDefault();pressed.set('key'+e.key,k);refreshInputs()}if(e.key==='w'&&!e.repeat)game.layer();if(e.key==='f'&&!e.repeat)game.interact()});addEventListener('keyup',e=>{pressed.delete('key'+e.key);refreshInputs()});
for(const type of ['contextmenu','selectstart','dragstart'])$('app').addEventListener(type,e=>{if(!e.target.closest('pre'))e.preventDefault()});
$('layer').onclick=()=>game.layer();$('interact').onclick=()=>game.interact();$('angle').onclick=()=>{view.inspect=!view.inspect;$('angle').textContent=view.inspect?'侧视':'斜视'};
$('pause').onclick=()=>{if(game.status!=='running')return;clearInput();game.pause(!game.paused);$('pause').textContent=game.paused?'继续':'暂停'};
$('telemetry').checked=telemetry.enabled;$('telemetry').onchange=e=>telemetry.consent(e.target.checked);
$('start').onclick=()=>{if(game.start()){$('modal').hidden=true;last=0;lastStatus='running'}};
function choices(){const root=$('choices');root.replaceChildren();const descriptions={cargo:'更多实体货物，增加防守长度',battery:'隧道照明更稳定；电池受损会失效',workshop:'维修更快，可花本局收益治疗'};for(const type of ['battery','workshop','cargo']){const b=document.createElement('button');b.textContent=DEFS[type].name;const small=document.createElement('small');small.textContent=descriptions[type];b.appendChild(small);b.className=type===selected?'selected':'';b.onclick=()=>{selected=type;choices()};root.appendChild(b)}}
$('more').onclick=()=>{if(game.more(selected)){clearInput();$('modal').hidden=true;game.start();view.cameraX=game.player.x;view.render(0);lastStatus='running'}};
$('cash').onclick=()=>{if(game.cashout()){try{localStorage.setItem('roundhouse_bank',String(game.bank));bankWritable=true}catch{bankWritable=false}showEnd()}};
$('restart').onclick=()=>{const bank=game.bank;game=new Game({bank,emit:(t,d)=>telemetry.log(t,d)});view.game=game;view.rebuildCars();view.cameraX=game.player.x;lastStatus='';$('modal').hidden=true;game.start();view.render(0)};
function showEnd(){clearInput();$('modal').hidden=false;$('start').hidden=true;$('cash').hidden=game.status!=='complete';$('more').hidden=game.status!=='complete';$('restart').hidden=!['lost','cashed'].includes(game.status);$('choices').hidden=game.status!=='complete';$('intro').textContent=game.status==='complete'?'列车已回到机库。损伤保留，选择一节新车厢后再出发。':game.status==='cashed'?'收益已存入机库银行。':'列车失守：本局未兑现收益清零，之前的银行存款保留。';$('summary').textContent='第 '+game.round+' 圈 · 未兑现 '+Math.round(game.money).toLocaleString()+' · 银行 '+Math.round(game.bank).toLocaleString()+(bankWritable?'':'（本次浏览器存储失败，尚未持久保存）');if(game.status==='complete')choices()}
function debugOpen(){clearInput();if(game.status==='running')game.pause(true);$('pause').textContent='继续';$('debug').hidden=false;debugRefresh()}
function debugRefresh(){$('remote').textContent=telemetry.status+' · SESSION '+telemetry.session;$('debugText').textContent=JSON.stringify(telemetry.report(),null,2)}
$('log').onclick=debugOpen;$('closeLog').onclick=()=>{$('debug').hidden=true};$('upload').onclick=async()=>{await telemetry.flush(true);debugRefresh()};$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify(telemetry.report()));$('remote').textContent='日志已复制'}catch{$('remote').textContent='复制不可用，可在下面长按选取日志'}};
let resizeTimer;function resize(){clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{const height=Math.min(innerHeight,window.visualViewport?.height||innerHeight);$('app').style.height=height+'px';view?.resize();const portrait=innerHeight>innerWidth;$('portrait').hidden=!portrait;if(portrait&&game.status==='running'){clearInput();game.pause(true);$('pause').textContent='继续'}},80)}
addEventListener('resize',resize);addEventListener('orientationchange',resize);window.visualViewport?.addEventListener('resize',resize);addEventListener('pageshow',resize);addEventListener('blur',()=>{clearInput();if(game.status==='running'){game.pause(true);$('pause').textContent='继续'}});document.addEventListener('visibilitychange',()=>{clearInput();if(document.hidden){if(game.status==='running')game.pause(true);$('pause').textContent='继续';telemetry.log('hidden');telemetry.flush(true)}else{last=0;resize();telemetry.log('visible')}});
$('game').addEventListener('webglcontextlost',e=>{e.preventDefault();fatal(new Error('WebGL context lost，请重新载入'))});addEventListener('error',e=>fatal(new Error(e.message)));addEventListener('unhandledrejection',e=>fatal(e.reason));
function ui(){$('round').textContent=String(game.round).padStart(2,'0');$('money').textContent=Math.round(game.money).toLocaleString();$('health').textContent=Math.round(game.cars[0].hp/game.cars[0].max*100)+' / '+Math.round(game.player.hp);$('weapon').textContent=game.weapon;$('attack').textContent=game.round>=3?'射击':'挥击';$('phase').textContent=({dock:'机库准备',depart:'出库 / 转盘对轨',yard:'工业装卸区',crane:'危险：机械臂',approach:'前方低净空隧道',tunnel:'隧道 / 车顶封闭',return:'返回机库'}[game.phase]||game.phase);$('fill').style.width=game.t*100+'%';$('event').textContent=game.event;$('layer').textContent=game.player.roof?'下车内':'上车顶';$('interact').textContent=game.player.carry?'放货':game.cars[game.currentCar].type==='engine'?'增压':game.cars[game.currentCar].type==='cargo'?'搬货':'交互';if(game.status!==lastStatus){lastStatus=game.status;if(['complete','lost','cashed'].includes(game.status))showEnd()}}
function frame(ts){if(frameError)return;try{const dt=last?Math.min(.05,(ts-last)/1000):0;last=ts;game.step(dt,input);view.render(dt);ui();requestAnimationFrame(frame)}catch(e){fatal(e)}}
try{view=new View($('game'),game,(t,d)=>telemetry.log(t,d));await view.init();$('start').disabled=false;$('start').textContent='从机库发车';$('event').textContent=game.event;resize();requestAnimationFrame(frame)}catch(e){fatal(e)}
window.__RH_DEBUG={snapshot,logs:()=>telemetry.events,renderer:()=>view.snapshot(),occlusion:()=>view.occlusion(),pixels:()=>view.pixels()};
if(new URLSearchParams(location.search).has('test'))window.__RH_TEST={game:()=>game,view:()=>view,step:(seconds)=>{for(let t=0;t<seconds;t+=.025)game.step(.025,{});view.render(.016);ui()},forceRoute:t=>{game.t=t;game.phase=phaseAt(t)},forceCars:n=>{while(game.cars.length<Math.min(12,n)){const d=DEFS.cargo;game.cars.push({type:'cargo',hp:d.hp,max:d.hp,cargo:3})}view.rebuildCars()},forcePlayer:(x,roof=false)=>{game.player.x=clamp(x,.4,game.length-.4);game.player.roof=roof;game.player.y=roof?ROOF:FLOOR;view.cameraX=game.player.x;view.render(.016)},reset:()=>{game=new Game({emit:(t,d)=>telemetry.log(t,d)});view.game=game;view.rebuildCars();view.cameraX=3;lastStatus='';return game.start()}};
