import {BUILD} from './sim.js?v=11';
export const V11_FINAL_SNAPSHOT_FIELDS=Object.freeze(['route','speedMode','routeProgress','playerLayer','playerLifeState','respawnRemaining','cargoUsed','cargoCapacity','cargoValue','scrap','meleeTier','rangedTier','batteryCharge','threatCurrent','threatCap','dev']);
export const V11_TELEMETRY_EVENTS=Object.freeze(['route_select','route_repeat','car_select','speed_change','emergency_stop','depot_enter','depot_exit','cargo_pickup','cargo_loaded','cargo_drop','cargo_lost','cargo_recovered','cargo_secured_at_dock','train_lost','player_death','respawn_start','respawn_complete','enemy_hit','enemy_kill','enemy_killed','scrap_gain','armory_open','armory_purchase','combat_tier_unlock','ranged_unlock','engine_state','engine_stalled','engine_recovered','engine_failed','repair_started','repair_complete','audio_unlock_attempt','audio_context_state','audio_first_sound','audio_resume_error','audio_unlock_error','mute_change','round_complete','cashout','one_more_round','prep_purchase','prep_equip','prep_use']);
// Temporary public test channel. No credentials, names, full URLs or input text.
const URL='https://ntfy.sh/roundhouse-log-f333c88ded8549f084c70bd5cceb0a7f';
export class Telemetry {
 constructor(snapshot,{dev=false,test=false,storage=globalThis.localStorage}={}){this.dev=!!dev;this.test=!!test;this.storage=storage;this.snapshot=snapshot;this.session=Date.now().toString(36).toUpperCase()+Math.random().toString(36).slice(2,6);this.events=[];this.seq=0;this.acked=0;this.sending=false;this.status='本地记录';this.errors=0;this.lastSend=0;this.failures=0;this.nextSend=0;this.live=globalThis.location?.hostname==='lys20001205.github.io'&&!this.dev&&!this.test;this.enabled=false;try{this.enabled=this.storage?.getItem('roundhouse_telemetry_consent')==='yes'}catch{};this.log('boot');this.timer=setInterval(()=>this.flush(),30000)}
 consent(value){this.enabled=value;try{this.storage?.setItem('roundhouse_telemetry_consent',value?'yes':'no')}catch{};this.log('telemetry_consent',{enabled:value});if(value)this.flush(true)}
 log(type,data={}){if(type.includes('error'))this.errors++;const item={...data,seq:++this.seq,ms:Math.round(performance.now()),type,dev:!!this.dev,test:!!this.test};this.events.push(item);if(this.events.length>300)this.events.shift();if(type.includes('error')||['engine_stalled','engine_recovered','run_failed','round_complete','cargo_recovered'].includes(type))this.flush(true);this.persist()}
 persist(){if(this.saveTimer)return;this.saveTimer=setTimeout(()=>{this.saveTimer=0;try{this.storage?.setItem('roundhouse_last_log',JSON.stringify(this.report()))}catch{}},1200)}
 dispose(){clearInterval(this.timer);clearTimeout(this.saveTimer);}
 report(){return{contract:'V11-L',dev:this.dev,test:this.test,v:BUILD,s:this.session,at:Date.now(),state:this.snapshot(),events:this.events.slice(-80),remote:{enabled:this.enabled,status:this.status,acked:this.acked,failures:this.failures},errors:this.errors}}
 async flush(force=false){if(!this.live||!this.enabled){this.status=this.enabled?'本地/CI：不上传':'本地记录（自动上传关闭）';return false}const now=Date.now();if(this.sending||now<this.nextSend||now-this.lastSend<(force?4000:29000))return false;const list=this.events.filter(e=>e.seq>this.acked).slice(0,12);if(!list.length&&!force)return false;const payload={v:BUILD,s:this.session,at:now,reason:'batch',state:this.snapshot(),events:list};let body=JSON.stringify(payload);while(new TextEncoder().encode(body).length>3500&&payload.events.length){payload.events=payload.events.slice(0,-1);body=JSON.stringify(payload)}if(new TextEncoder().encode(body).length>3500){this.status='快照过大；保留本地日志';return false}this.sending=true;this.lastSend=now;this.status='发送中';const ctl=new AbortController(),timeout=setTimeout(()=>ctl.abort(),8000);try{const r=await fetch(URL,{method:'POST',body,signal:ctl.signal,credentials:'omit',keepalive:true});if(!r.ok)throw Error('HTTP '+r.status);const receipt=await r.json();if(!receipt.id)throw Error('missing receipt');this.acked=Math.max(this.acked,...payload.events.map(e=>e.seq));this.status='已接收 '+new Date().toLocaleTimeString();this.nextSend=0;return true}catch(e){this.failures++;this.status='上传失败；本地日志仍保留';this.nextSend=now+Math.min(180000,30000*this.failures);return false}finally{clearTimeout(timeout);this.sending=false}}
}
