import * as T from '../vendor/three.module.min.js';
import {LENGTH,FLOOR,ROOF,clamp,B} from './sim.js?v=10';
import {Feedback3D} from './feedback3d.js?v=10';
const v=new T.Vector3();
export class View {
 constructor(canvas,game,log){this.game=game;this.log=log;this.canvas=canvas;this.frames=0;this.loaded=0;this.carCount=0;this.inspect=false;this.cameraX=game.player.x;this.syncs=0;this.enemyModels=new Map();this.enemyPool=[];this.enemyMaterials=new Map();this.cylinderCache=new Map();this.bulletPool=[];this.particlePool=[];this.matCache=new Map();
  this.renderer=new T.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'low-power'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.22;
  this.scene=new T.Scene();this.scene.background=new T.Color(0x20384a);this.scene.fog=new T.Fog(0x20384a,48,105);this.camera=new T.OrthographicCamera(-20,20,5,-5,.1,150);
  this.hemi=new T.HemisphereLight(0xccecff,0x25322d,1.65);this.scene.add(this.hemi);this.sun=new T.DirectionalLight(0xffe1ad,2.7);this.sun.castShadow=true;Object.assign(this.sun.shadow.camera,{left:-24,right:24,top:20,bottom:-20,near:.1,far:65});this.sun.shadow.mapSize.set(1024,1024);this.sun.shadow.bias=-.0015;this.sun.shadow.normalBias=.035;this.scene.add(this.sun,this.sun.target);
  this.train=new T.Group();this.scene.add(this.train);this.carGroup=new T.Group();this.actorGroup=new T.Group();this.train.add(this.carGroup,this.actorGroup);this.ground=new T.Group();this.scene.add(this.ground);this.box(this.ground,0,-.23,0,220,.4,110,0x253c45).receiveShadow=true;
  this.yard=new T.Group();this.scene.add(this.yard);this.yardProps=[];for(let i=0;i<17;i++){const g=new T.Group();const x=i*9-70;g.userData.offset=x;g.position.set(x,0,-9-(i%3)*4);this.box(g,0,2+(i%3),0,6,4+(i%3)*2,4,i%2?0x506779:0x435c66);this.box(g,0,4.2+(i%3)*2,0,6.4,.25,4.3,0x9ba8a6);for(let k=0;k<3;k++)this.box(g,-1.8+k*1.8,3+(i%3),2.04,1.1,.7,.08,0xa8c8c8);this.cyl(g,2.5,5+(i%3),-1,.38,3,0x77918c);this.yard.add(g);this.yardProps.push(g)}
  this.dock=new T.Group();this.scene.add(this.dock);this.deck=new T.Group();this.dock.add(this.deck);this.platform=this.cyl(this.deck,0,.02,0,13,.18,0x587682,48);this.rim=new T.Mesh(new T.TorusGeometry(13,.14,6,64),this.mat(0xe1b961));this.rim.rotation.x=Math.PI/2;this.rim.position.y=.14;this.deck.add(this.rim);
  for(let i=0;i<7;i++){const gate=new T.Group(),a=Math.PI*.15+i*Math.PI*.70/6;gate.position.set(Math.cos(a)*18,0,-Math.sin(a)*20);gate.rotation.y=-a+Math.PI/2;this.box(gate,0,3.4,0,5.8,6.8,.6,0x455c6b);this.box(gate,0,2.8,.36,4.5,5.2,.1,0x132735);this.box(gate,0,5.7,.6,4.6,.20,.24,0xe0b35e);this.dock.add(gate)}
  this.track=new T.Group();this.scene.add(this.track);for(const z of [-.9,.9])this.box(this.track,0,.14,z,220,.18,.13,0x8a9c9f);this.sleepers=[];for(let i=0;i<48;i++){const s=this.box(this.track,i*2-48,.025,0,1.05,.20,2.6,0x463f30);s.userData.offset=i*2-48;this.sleepers.push(s)}
  this.crane=new T.Group();this.scene.add(this.crane);this.box(this.crane,0,4.5,-4,1,9,1,0xdaa13e);this.box(this.crane,0,7,-1.5,.75,.60,6,0xeac15e);this.cyl(this.crane,0,6.1,.6,.10,1.7,0x93a7ae);this.box(this.crane,0,5.22,.6,2.35,.48,1.2,0xe2aa3e);for(let k=-2;k<=2;k++)this.box(this.crane,k*.42,4.95,1.2,.22,.06,.05,0x3e3830);
  this.tunnel=new T.Group();this.scene.add(this.tunnel);for(let i=0;i<13;i++){const x=i*7-35;this.box(this.tunnel,x,2.8,-2.8,.5,5.6,.6,0x63717b);this.box(this.tunnel,x,5.4,-1.3,.5,.5,3.6,0x63717b);this.box(this.tunnel,x,4.65,-2.4,.6,.10,.18,0xf0ce89);this.box(this.tunnel,x+3.5,2.3,-3.3,6.5,4.6,.3,0x303f4b)}
  this.lamps=new T.PointLight(0xccecff,15,13,1.5);this.train.add(this.lamps);this.lamps.position.set(3,3,.1);
  this.rangeLine=new T.Line(new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(2,0,0)]),new T.LineDashedMaterial({color:0xf5c678,dashSize:.18,gapSize:.13,transparent:true,opacity:.68}));this.train.add(this.rangeLine);
  this.bulletGroup=new T.Group();this.train.add(this.bulletGroup);this.particles=new T.Group();this.train.add(this.particles);this.projectileGeometry=new T.BoxGeometry(.38,.065,.07);this.particleGeometry=new T.BoxGeometry(.075,.075,.075);this.juice=new Feedback3D(this);this.resize();
 }
 mat(c){if(!this.matCache.has(c))this.matCache.set(c,new T.MeshStandardMaterial({color:c,roughness:.84,metalness:.10}));return this.matCache.get(c)}
 box(g,x,y,z,sx,sy,sz,c){this.cube??=new T.BoxGeometry(1,1,1);const m=new T.Mesh(this.cube,this.mat(c));m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
 cyl(g,x,y,z,r,h,c,segments=12){const m=new T.Mesh((this.cylinderCache.get(segments)||(()=>{const g=new T.CylinderGeometry(1,1,1,segments);this.cylinderCache.set(segments,g);return g})()),this.mat(c));m.position.set(x,y,z);m.scale.set(r,h,r);m.castShadow=true;m.receiveShadow=true;g.add(m);return m}
 async init(){const loader=new T.ObjectLoader();[this.carTemplate,this.robotTemplate,this.crateTemplate]=await Promise.all(['train-cutaway','crew-robot','cargo-crate'].map(n=>loader.loadAsync(new URL('../assets/'+n+'.json?v=10',import.meta.url).href)));this.loaded=3;this.playerRig=this.makeRobot(false);this.actorGroup.add(this.playerRig);this.rebuildCars();this.log('models_loaded',{count:3});this.render(0)}
 makeRobot(enemy){const m=this.robotTemplate.clone(true);m.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(enemy&&o.material.vertexColors){if(!this.enemyMaterials.has('body')){const material=o.material.clone();material.color.setHex(0xe39494);this.enemyMaterials.set('body',material)}o.material=this.enemyMaterials.get('body')}}});m.userData.arm=m.getObjectByName('WeaponArm');m.userData.wrench=m.getObjectByName('Wrench');m.userData.gun=m.getObjectByName('Sidearm');m.userData.legL=m.getObjectByName('LegL');m.userData.legR=m.getObjectByName('LegR');const carried=this.crateTemplate.clone(true);carried.name='CarriedCargo';carried.scale.setScalar(.72);carried.position.set(.4,.59,.51);m.add(carried);m.userData.carried=carried;return m}
 rebuildCars(){this.carGroup.clear();this.carCount=this.game.cars.length;this.cars=[];const tags=document.getElementById('carTags');tags.replaceChildren();this.game.cars.forEach((c,i)=>{const m=this.carTemplate.clone(true);m.name='Car-'+i;m.position.x=i*LENGTH+4.15;m.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true}});this.carGroup.add(m);const props=new T.Group();m.add(props);if(c.type==='engine'){this.box(props,-2.4,1.65,-.65,2,1.05,1.0,0x314e62);this.box(props,-2.4,2.2,-.6,1.7,.12,.8,0xdeae58);this.cyl(props,-2.5,2.50,-.65,.35,.5,0x638b9d);this.box(props,1.65,1.75,-.8,1.6,1.15,.5,0x5e7885);this.box(props,1.65,2.34,-.6,1.2,.15,.15,0x79d7c4)}
 if(c.type==='battery')for(const x of [-2.3,-1.2,1.5]){this.box(props,x,1.95,-.85,.8,1.7,.65,0x366458);this.box(props,x,2.47,-.5,.55,.08,.04,0xb0f0bf)}
 if(c.type==='workshop'){this.box(props,-1.8,1.8,-.7,2.7,.18,1.0,0xc9a266);for(const x of [-2.8,-.8])this.box(props,x,1.4,-.7,.15,.7,.6,0x718e96);this.box(props,-1.5,2.02,-.7,.8,.25,.4,0x497486)}
 const crates=[];if(c.type==='cargo')for(let k=0;k<7;k++){const cr=this.crateTemplate.clone(true);cr.position.set(-2.7+(k%3)*1.2,1.1+Math.floor(k/3)*.76,-.68);props.add(cr);crates.push(cr)}
 const hp=this.box(m,0,1.22,1.64,5,.06,.045,0x8cdaa1);hp.castShadow=false;const tag=document.createElement('div');tag.className='tag';tags.appendChild(tag);this.cars.push({m,crates,hp,tag})});
 const r=Math.max(12,this.game.length*.58);this.platform.scale.set(r,.18,r);this.rim.scale.set(r/13,r/13,1);this.dock.position.x=this.game.length*.5;
 }
 resize(){const r=this.canvas.getBoundingClientRect();this.w=Math.max(1,r.width);this.h=Math.max(1,r.height);this.renderer.setSize(this.w,this.h,false);this.syncs++;this.log('viewport',{css:[this.w,this.h],backing:[this.canvas.width,this.canvas.height]})}
 project(x,y,z=.65){v.set(x,y,z);this.train.localToWorld(v);v.project(this.camera);return{x:(v.x*.5+.5)*this.w,y:(-.5*v.y+.5)*this.h,z:v.z}}
 poseRobot(rig,p,dt,isEnemy=false){rig.position.set(p.x,p.y,.65);rig.rotation.y=p.face<0?Math.PI:0;const d=rig.userData;d.carried.visible=!!p.carry;d.gun.visible=!p.carry&&!isEnemy&&this.game.round>=3&&!this.game.repairJob;d.wrench.visible=!p.carry&&!d.gun.visible;const progress=p.swing>0?(1-p.swing/.36):0;d.arm.rotation.z=p.swing>0?1.20-progress*2.3:-.20;if(d.gun.visible)d.arm.rotation.z=0;if(!isEnemy&&this.game.repairJob)d.arm.rotation.z=-.3+Math.sin(this.game.elapsed*16)*.18;const motion=(!isEnemy&&this.moving)||isEnemy;const walk=motion?Math.sin(this.game.elapsed*13)*.26:0;d.legL.rotation.z=walk;d.legR.rotation.z=-walk;rig.scale.setScalar(isEnemy?1:1.07)}
 render(dt){if(!this.playerRig)return;const g=this.game,p=g.player;this.moving=Math.abs(p.x-(this.previousX??p.x))>.002;this.previousX=p.x;if(g.cars.length!==this.carCount)this.rebuildCars();
  const routeRunning=g.status==='running'&&!g.paused;const atDock=['dock','depart','return'].includes(g.phase);this.dock.visible=atDock;this.yard.visible=!atDock&&g.phase!=='tunnel';this.tunnel.visible=g.phase==='tunnel'||g.phase==='approach';this.crane.visible=g.phase==='crane';
  this.crane.position.x=g.craneX;this.crane.position.y=(g.t<.34?1.2:0);this.tunnel.position.x=Math.round(p.x/7)*7;
  const rotation=g.phase==='depart'?(.22*(1-clamp(g.t/.09,0,1))):g.phase==='dock'?.22*(g.status==='arriving'?clamp(g.arrivalElapsed/B.arrivalTime,0,1):1):0;this.train.rotation.y=rotation;const pivot=g.length*.5;this.train.position.set(pivot*(1-Math.cos(rotation)),0,pivot*Math.sin(rotation));this.deck.rotation.y=rotation;
  const travel=g.t*300;for(const prop of this.yardProps)prop.position.x=(((prop.userData.offset-travel*.5)%140)+140)%140-40+p.x*.22;
  this.track.position.x=Math.floor(p.x/25)*25;for(const sl of this.sleepers)sl.position.x=sl.userData.offset-(travel%2);
  this.ground.position.x=p.x;this.cars.forEach(({m,crates,hp,tag},i)=>{const c=g.cars[i];m.visible=Math.abs(m.position.x-p.x)<42;hp.scale.x=5*Math.max(.01,c.hp/c.max);crates.forEach((o,k)=>o.visible=k<c.cargo);m.traverse(o=>{if(o.name==='Wheel'&&routeRunning)o.rotation.z=-travel*2});tag.textContent=String(i+1).padStart(2,'0')+' '+({engine:'动力',cargo:'货物',battery:'供电',workshop:'维修'}[c.type])+' '+Math.round(c.hp/c.max*100)+'%'});
  this.poseRobot(this.playerRig,p,dt);const ids=new Set(g.enemies.map(e=>e.id));for(const [id,m] of this.enemyModels)if(!ids.has(id)){this.actorGroup.remove(m);this.enemyPool.push(m);this.enemyModels.delete(id)}
  for(const e of g.enemies){let m=this.enemyModels.get(e.id);if(!m){m=this.enemyPool.pop()||this.makeRobot(true);this.enemyModels.set(e.id,m);this.actorGroup.add(m)}this.poseRobot(m,{...e,face:e.x>p.x?-1:1,swing:e.wind>0?.36-e.wind*.4:0},dt,true);if(e.climb>0)m.position.y-=e.climb*1.5;m.scale.setScalar(e.flash>0?1.10:1);m.userData.gun.visible=false;m.userData.wrench.visible=!e.carry}
  this.bulletPool.forEach(m=>m.visible=false);g.projectiles.forEach((b,i)=>{let m=this.bulletPool[i];if(!m){m=new T.Mesh(this.projectileGeometry,this.mat(0xffe09b));this.bulletPool.push(m);this.bulletGroup.add(m)}m.visible=true;m.position.set(b.x,b.y,b.z??.8854)});
  this.particlePool.forEach(m=>m.visible=false);let particleIndex=0;for(const f of g.effects){for(let i=0;i<(f.type==='swing'?0:4);i++){const u=(1-f.life/f.max),a=i*1.71;let m=this.particlePool[particleIndex++];if(!m){m=new T.Mesh(this.particleGeometry);this.particlePool.push(m);this.particles.add(m)}m.visible=true;m.material=this.mat(['repair','restart'].includes(f.type)?0x98f3ad:f.type==='damage'?0xf07662:0xffd38a);m.position.set(f.x+Math.cos(a)*u,f.y+Math.sin(a)*u+.2,.9);m.scale.setScalar(Math.max(.2,1.5-u));}}
  const muzzle=g.muzzle(),pts=this.rangeLine.geometry.attributes.position;pts.setXYZ(0,muzzle.x,muzzle.y,.89);pts.setXYZ(1,muzzle.x+p.face*g.range,muzzle.y,.89);pts.needsUpdate=true;this.rangeLine.geometry.computeBoundingSphere();this.rangeLine.computeLineDistances();this.rangeLine.visible=g.status==='running';
  const isTunnel=g.phase==='tunnel';this.hemi.intensity=isTunnel?.5+.3*g.power:1.65;this.sun.intensity=isTunnel?.55:2.7;const flicker=g.batteryBand==='flicker'&&!this.reducedMotion?(.94+.06*Math.sin(g.elapsed*12)):1;this.lamps.intensity=isTunnel?(10+14*g.power)*flicker:0;this.lamps.color.setHex(g.power>.25?0xccecff:0xefb29a);this.lamps.position.x=p.x;this.juice.update();
  this.scene.background.setHex(isTunnel?0x101b26:atDock?0x203241:0x284455);this.scene.fog.color.copy(this.scene.background);
  const desiredX=p.x;this.cameraX+=(desiredX-this.cameraX)*(1-Math.exp(-dt*14));if(Math.abs(this.cameraX-desiredX)>8)this.cameraX=desiredX;
  const aspect=this.w/this.h,vertical=7.7;this.camera.left=-vertical*aspect/2;this.camera.right=vertical*aspect/2;this.camera.top=vertical/2;this.camera.bottom=-vertical/2;this.camera.updateProjectionMatrix();
  this.train.updateMatrixWorld(true);const target=new T.Vector3(this.cameraX,2.7,.1).applyMatrix4(this.train.matrixWorld);this.camera.position.copy(target).add(new T.Vector3(this.inspect?8:1.2,this.inspect?9:7,29));this.camera.lookAt(target);this.camera.updateMatrixWorld(true);this.sun.position.set(p.x-8,18,10);this.sun.target.position.set(p.x,0,0);const restart=g.effects.find(f=>f.type==='restart');if(restart&&!this.reducedMotion)this.camera.position.y+=Math.sin(g.elapsed*36)*.05*restart.life;this.renderer.render(this.scene,this.camera);this.frames++;
  this.cars.forEach(({m,tag})=>{const pos=this.project(m.position.x,.45,1.7);tag.style.left=pos.x+'px';tag.style.top=pos.y+'px';tag.hidden=!m.visible||pos.x<0||pos.x>this.w;});
  const s=this.project(p.x,p.y+1.85,.7);const tag=document.getElementById('playerTag');tag.style.left=s.x+'px';tag.style.top=s.y+'px';tag.hidden=s.x<0||s.x>this.w;tag.textContent=p.carry?'YOU · 搬运':p.roof?'YOU · 车顶':'YOU · 车内';
 }
 snapshot(){if(!this.carTemplate)return{modelsLoaded:this.loaded,drawCount:this.frames};const p=this.game.player,screen=this.project(p.x,p.y+1,.65);let meshes=0;this.scene.traverse(o=>{if(o.isMesh)meshes++});return{renderer:this.renderer.getContext() instanceof WebGL2RenderingContext?'WebGL2':'unknown',modelDepth:new T.Box3().setFromObject(this.carTemplate).getSize(new T.Vector3()).z,threeRevision:T.REVISION,modelsLoaded:this.loaded,meshCount:meshes,triangles:this.renderer.info.render.triangles,drawCalls:this.renderer.info.render.calls,drawCount:this.frames,canvasSyncCount:this.syncs,canvasCss:[this.w,this.h],canvasBacking:[this.canvas.width,this.canvas.height],cameraX:this.cameraX,playerScreenX:screen.x,playerScreenY:screen.y,viewportHeight:this.h,inspect:this.inspect,gpuGeometries:this.renderer.info.memory.geometries,enemyPool:this.enemyPool.length}}
 muzzle(){const node=this.playerRig.getObjectByName('Muzzle');const p=node.getWorldPosition(new T.Vector3());this.train.worldToLocal(p);return {x:p.x,y:p.y,z:p.z}}
 occlusion(){const p=this.game.player;const target=new T.Vector3(p.x,p.y+1,.65);this.train.localToWorld(target);const origin=target.clone().add(new T.Vector3().subVectors(this.camera.position,new T.Vector3(this.cameraX,2.7,.1)).normalize().multiplyScalar(30));const ray=new T.Raycaster(origin,target.clone().sub(origin).normalize(),.01,29.6);return ray.intersectObjects(this.carGroup.children,true).filter(h=>h.object.visible).map(h=>h.object.name).slice(0,10)}
 pixels(){this.renderer.render(this.scene,this.camera);const gl=this.renderer.getContext(),data=new Uint8Array(4);gl.readPixels(Math.floor(this.canvas.width/2),Math.floor(this.canvas.height/2),1,1,gl.RGBA,gl.UNSIGNED_BYTE,data);return [...data]}
}
